### ISSUE TITLE
enforceDefaultMessage = false doesn't work with defineMessages

### ISSUE THREAD

**Issue by Ne3l** [formatjs/formatjs-old#101]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
When not defining defaultMessages while using `defineMessages` api that `react-intl` provides it crashes. it works with `<FormattedMessage />` component.

**To Reproduce**

1. Add

```js
const messages = defineMessages({
  test: {
    id: 'TRANSLATION_KEY'
  },
});
```

2. set option `enforceDefaultMessage` to `false` in `babel-plugin-react-intl`  
3. Run babel on this file

**Expected behavior**
`TRANSLATION_KEY` is extracted properly

**Desktop (please complete the following information):**

- OS: Macos 10.14.2
- Node 10.15.1

**Comment by longlho** [comment]
Would you mind providing a repro example and/or stack trace? I added at test in #104 and it seems to be working fine

**Comment by longlho** [comment]
close due to stale
