### ISSUE TITLE
Best way to provide context descriptions to translators using babel-plugin-react-intl

### ISSUE THREAD

**Issue by ma7erick** [formatjs/formatjs-old#106]
I am using `babel-plugin-react-intl`

I would like to somehow make my `description` fields from my message definitions to be available to see in one place for my translator. I'm not sure what the best way to accomplish this is, but I would like for my generated json files to look something like this:
```
{
  "a.login": {
    "message": "Login",
    "description": "Label for login button"
  },
  "a.cancel": {
    "message": "Cancel",
    "description": "Label for cancel button"
  }
}
```

But instead, its seems like I'm only produce a file with the id paired with its translation:
```
{
  "a.login": "Login",
  "a.cancel": "Cancel"
}
```

I am using `babel-plugin-react-intl` in addition to `react-intl-translations-manager` to generate my single json file with all of my translations.  What is the best way to deliver translations with their descriptions to a translator so that they have some context while translating?

**Comment by longlho** [comment]
I'm not sure how `react-intl-translations-manager` works but the `babel-plugin-react-intl` itself gives you all that information, just not merged. In the future we might be providing a CLI to do this kind of task
