### ISSUE TITLE
`locales` param could be mutated

### ISSUE THREAD

**Issue by lorenzorad** [formatjs/formatjs-old#11]
The check if `locales` parameter is an array modifies the original object/string/whatever type. 
`
 if (!Array.isArray(locales)) {
        locales = [locales];
    }
`

Could be more useful to copy the original object into a new one? Example:
`var localesAsArray = Array.isArray(locales) ? locales : [locales];`

And then use that copy in the code:
`
...
var supportedLocales = intlConstructor.supportedLocalesOf(localesAsArray);
...
`

**Comment by longlho** [comment]
that shouldn't mutate `locales` like @cloud-walker said
