### ISSUE TITLE
Double commas for some select/plural

### ISSUE THREAD

**Issue by Betree** [formatjs/formatjs-old#117]
**Which package?**
`babel-plugin-react-intl@4.0.0` -> `babel-plugin-react-intl@4.1.1`

**Describe the bug**
We're trying to migrate from `3.5.1` to `4.1.1` and our translations update produces a change that I do not fully understand for `select` and `plural`.

Strings that used to be extracted like:

```json
"collective.types.collective": "{n, plural, one {collective} other {collectives}}"
```

Are now extracted as:

```json
"collective.types.collective": "{n,plural,,one{collective} other{collectives}}",
```

Removing spaces is a good change that's going to clarify things for translators. The part that confuses me is the two commas `,,`. Looking at [the documentation](https://formatjs.io/guides/message-syntax/#select-format) I don't see any example of such pattern. The changelog isn't helping either. 

Note that this additional comma is not added for every select or plural, just for some of them.

**To Reproduce**

- Check https://github.com/opencollective/opencollective-frontend/pull/2171/commits/6be245877e0394280e2439dce5fc3f13e13c1744 for a list of changes in extracted strings due to this update.

- You can also checkout https://github.com/opencollective/opencollective-frontend/pull/2171 if you want to reproduce locally. We use the `npm run build:langs` command to update the language files that relies on the following script: https://github.com/opencollective/opencollective-frontend/blob/282058de4366e9ad17094e0db7ea8ae5fa410b86/scripts/translate.js

**Expected behavior**

- There should be only one comma, or the documentation should explain what is this syntax.
- Ideally this should be predictable: an update for a single string require translators to update the matching string for 7 languages on our side, which can represent a lot of work for them.

---

PS: Thanks for this great project!

**Comment by longlho** [comment]
Thanks for reporting I’ll take a look soon. We rewrote our AST & its
printer so it might be a side effect since plural accepts offset & since
there’s no offset in this case we might be printing out empty string but
still concat w , is my suspicion

**Comment by Betree** [comment]
Thanks @longlho, let me know if I can help with anything.

**Comment by daggmano** [comment]
Not sure if this is related (it does include the double commas), but there is more mangling going on.

Input default message, which matches output from 3.5.1:
    `"{count, plural, one {# file} other {# files}}"`

Output from 4.0.0 onwards:
    `"{count,plural,,one{{count, 2} file} other{{count, 2} files}}"`

Or is this new format (apart from the commas) intentional? Currently it fails with
`SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "2" found.`

**Comment by longlho** [comment]
Yup it is. I’ll take a look next week after vacation

**Comment by guopengliang** [comment]
I am experiencing a similar issue as @daggmano points out. When I try to extract messages including `number`, `date` and `select`, the extracted output would replace these strings to `2`, `3` and `5`.

I am using `react-intl@3.0.0-beta.18` and `babel-plugin-react-intl@4.1.0`. This is an issue with the `printAST` function (from dependency `intl-messageformat-parser@2.1.0`, which did not convert these enum types to strings.
