### ISSUE TITLE
Ignore non-statically evaluate-able for extraction messages

### ISSUE THREAD

**Issue by lucasriondel** [formatjs/formatjs-old#119]
### Which package?

babel-plugin-react-intl

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

There are some lines in my code where `FormattedMessage` uses an id that cannot be evaluated during babel's work. Currently, it gives me a `SyntaxError: [React Intl] Messages must be statically evaluate-able for extraction.`, but can you add an option to disable that behavior and just ignore the message ? 

### Expected behavior

An option such as `ignoreNonStaticIds` with a `false` default value would be great.

### Current behavior

Babel stops its execution.

**Comment by longlho** [comment]
What's the use case for intentionally ignoring this?
