### ISSUE TITLE
Exception when using plural in safari

### ISSUE THREAD

**Issue by stefk** [formatjs/formatjs-old#123]
**Which package?**

messageformat -> format-cache

**Describe the bug**

Translating a string containing a plural rule leads to the following error in Safari:

```
TypeError: undefined is not an object (evaluating '(_a = FormatConstructor).bind')
```

The original line is here: https://github.com/formatjs/formatjs/blob/master/packages/intl-format-cache/src/index.ts#L43. For some reason, `FormatConstructor` seems to be undefined in Safari (the same exact code works fine in Chrome).

**To Reproduce**

This basic example from the docs is enough to raise the error:

```js
new IntlMessageFormat(
  'You have {numPhotos, plural, ' +
  '=0 {no photos.}' +
  '=1 {one photo.}' +
  'other {# photos.}}'
);
```

**Expected behavior**

No error ;)

**Desktop**

- MacOS Mojave 10.14.5
- Safari 12.1.1

**Comment by longlho** [comment]
That's bc Safari has no `Intl.PluralRules` so you'd have to polyfill it (see https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#modern-intl-dependency for more details)

**Comment by stefk** [comment]
I guess this can be closed then. But the docs are a bit misleading IMHO:

> Intl is present in all modern browsers (IE11+) 

Thanks for the quick reply.
