### ISSUE TITLE
Allow selection of thresholds in selectUnit

### ISSUE THREAD

**Issue by lithin** [formatjs/formatjs-old#125]
**Which package?**
`intl-utils`

**Is your feature request related to a problem? Please describe.**
When using `selectUnit`, it adds `quarter` as one of the thresholds which doesn't really make sense in many languages, despite CLDR definitions.

**Describe the solution you'd like**
We could use the `Threshold` interface or similar to disable some of the thresholds using boolean values. It could be then something like `selectUnit(start, end, { quarter: false })`.

I'm not sure about coupling the original `Threshold` interface (using numbers to change where threshold appears) and one where we'd use `boolean`s to determine if threshold should appear at all. Possibly cleaner solution would be `selectUnit(start, end, DEFAULT_THRESHOLDS, { quarter: false })` but that extends the number of arguments which already isn't small.

What are your thoughts? I'm happy to write it up once we know what api we'd prefer :)

**Describe alternatives you've considered**
I considered writing a wrapper in our app but thought this is a common-enough use-case that others could benefit from as well.

**Additional context**
 Full discussion here: https://github.com/formatjs/react-intl/issues/1370

**Comment by longlho** [comment]
I think `selectUnit(start, end, { quarter: false })` is fine so go ahead!

**Comment by lithin** [comment]
Cool! :)

**Comment by longlho** [comment]
fixed by #138
