### ISSUE TITLE
Error when installing the intl-relativetimeformat polyfill on iOS 9

### ISSUE THREAD

**Issue by janicduplessis** [formatjs/formatjs-old#128]
**Which package?**
intl-relativetimeformat

**Describe the bug**
On iOS 9 the polyfill crashes when defining the name prop for the polyfilled functions (https://github.com/formatjs/formatjs/blob/master/packages/intl-relativetimeformat/src/polyfill.ts#L61). Probably a bug in JavaScriptCore since it doesn't happen on older iOS versions.

**To Reproduce**
This currently happens on start when including the polyfill in a react native app on iOS 9. (react native uses the system JSC)

Not sure if it also happens on Safari.

**Expected behavior**
It doesn't crash

**Screenshots**

![image](https://user-images.githubusercontent.com/2677334/61980815-c466cb80-afc5-11e9-9085-a4dbcc93bc41.png)

**Smartphone (please complete the following information):**

- Device: iPhone6
- OS: iOS 9.3
- Browser: React Native (JSC)
- Version: N/A

**Additional context**
Workaround: removing https://github.com/formatjs/formatjs/blob/master/packages/intl-relativetimeformat/src/polyfill.ts#L61-L76 fixes the issue.

**Comment by longlho** [comment]
PR'd be very appreciated since I don't use react-native. Personally I'm ok w/ try-catch the whole thing. Most operations there are so that `intl-relativetimeformat` is as close to spec as possible (enforced by test262)

**Comment by janicduplessis** [comment]
@longlho Makes sense, I opened a PR with the fix #129
