### ISSUE TITLE
Colon breaks messageformat

### ISSUE THREAD

**Issue by klimashkin** [formatjs/formatjs-old#135]
**Which package?**
`intl-messageformat` 6.0.0

**Describe the bug**
Since 6.0.0 this string throws an error
`'{when, date, L} at {when, date, HH:mm:ss} by {name}'`

```
Uncaught SyntaxError: Expected "}" but ":" found.
    at peg$buildStructuredError (app.js:198386)
    at peg$parse (app.js:200129)
    at Function.parse [as __parse] (app.js:197956)
    at new IntlMessageFormat (app.js:200477)
```
where
```
'HH:mm:ss': {
  hour: TWO_DIGIT, minute: TWO_DIGIT, second: TWO_DIGIT,
  hour12: false,
},
```

**Expected behavior**
That should produce something like
`06/26/2019 at 08:41:07 by Paul`

**Comment by longlho** [comment]
Thanks for reporting, we'll take a look asap. cc @pyrocat101

**Comment by longlho** [comment]
6.0.1 should have this fix
