### ISSUE TITLE
Plural format using defineMessages

### ISSUE THREAD

**Issue by youdz** [formatjs/formatjs-old#137]
**Which package?**
`babel-plugin-react-intl`, version 4.1.5 (current latest)

**Describe the bug**
Messages using plural formatting are being transformed by `babel-plugin-react-intl` and throw errors when given to a `FormattedMessage` component from `react-intl`.

**To Reproduce**
1. Use definesMessages to declare a simple plural string.
```javascript
const messages = defineMessages({
    kittens: {
        id: "app.home.kittens",
        description: "Counts kittens",
        defaultMessage: "{count, plural, =0 {😭} one {# kitten} other {# kittens}}"
    }
});
```
2. Use the created `MessageDescriptor` as props for a FormattedMessage
```jsx
<FormattedMessage {...messages.kittens} values={{count: 42}}/>
```
3. See that the extracted JSON is:
```json
{
  "id": "app.home.kittens",
  "description": "Counts kittens",
  "defaultMessage": "{count,plural,,=0{😭} one{{count, 2} kitten} other{{count, 2} kittens}}"
}
```
4. Run the app, it throws the following error:
```
[React Intl] Error formatting the default message for: "app.home.kittens"
SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "2" found.
```

Note that the same code without `defineMessages()` works completely fine, but of course the message isn't extracted as JSON.

**Expected behavior**
Extracted MessageDescriptors should not be broken by extracting them.

**Desktop (please complete the following information):**

- OS: OSX
- Browser: latest Chrome at the time of filing this issue: Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by longlho** [comment]
What version are you using? Can you make sure it’s the latest?

**Comment by youdz** [comment]
Looks like I'm still on 4.1.0.

There is a bake time for open-source packages to be usable where I work, so I can't upgrade yet. I'll hack around to at least test locally with 4.1.5 to see if it fixes, and I'll keep you updated.

Just curious, since this is a monorepo I can't find package release notes for `babel-plugin-react-intl`: are you thinking of some changes in particular in the last couple weeks of releases that fixed similar issues? Thanks.

**Comment by youdz** [comment]
Ok, the hack wasn't that hard of a hack, so I was able to test with **4.1.5** already. The issue is still there even with latest `babel-plugin-react-intl`.

I'll update the opening post.

**Comment by longlho** [comment]
intl-messageformat-parser is where the issue got fixed so you might need to
unpin that as well

**Comment by youdz** [comment]
Ok, so I tried again with these versions:
* `react-intl@3.0.0-beta.23`
* `babel-plugin-react-intl@4.1.5`
* `intl-messageformat-parser@3.0.1`

The default message is still transformed into
```
{count,plural,,=0{😭} one{{count, 2} kitten} other{{count, 2} kittens}}
```
but this time instead of the previous error message I get 
```
[React Intl] Error formatting the default message for: "app.home.kittens"
SyntaxError: Expected "=", "offset:", or keyword but "," found.
```

**Comment by longlho** [comment]
this is the commit that fixed the issue u mentioned: bebdf9534ed7a193d7d56d4dac11a4e0c7111d91

I've also added the string u mentioned in the test (0c34ee46f87459853ceef3a92309e77a5dd4b82c) and it's behaving as I expected :-/ Are you sure you've got latest versions of things?

**Comment by youdz** [comment]
I just went through my `package-lock.json` to make sure that some nested dependency wasn't using an older version of `intl-messageformat-parser`. I can confirm that all of them are using `3.0.1`.

I'm moving forward with an alternative solution to get unblocked, and as I said there is this "bake time" which isn't helping me much. I'll let it sit for a bit and try again in a couple weeks, maybe some other dependency in there is not completely up-to-date. I'll post an update here if it ends up working. Thank you for your help.

**Comment by longlho** [comment]
Thanks a lot for reporting!

**Comment by youdz** [comment]
Well, reporting is easy when you're so reactive. 👍 on that.
