### ISSUE TITLE
selectUnit incorrectly returns quarter

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs-old#139]
**Which package?**
intl-utils

**Describe the bug**
Expecting to return months if with 3 months, but the library returns quarter instead.

**To Reproduce**

```js
import { intl-utils } from '@formatjs/intl-utils';

// test case 1
const from = new Date('2019-06-29T17:15:54.723Z');
const to = new Date('2019-08-06T05:29:00.632Z');

selectUnit(from, to);
// { value: -1, unit: 'quarter' }

// test case 2
const from2 = new Date('2019-06-05T05:44:12.926Z');
selectUnit(from2, to);
// { value: -1, unit: 'quarter' }

```

**Expected behavior**

Expect the return should be `{ value: -1, unit: 'month' }` on the test case and `{ value: -2, unit: 'month' }` for the second test case

https://repl.it/repls/WorseMintyScript

**Comment by longlho** [comment]
This is unfortunately a side effect of how non-deterministic calendar-based time difference can be :( I think your PR to explicitly turn off `quarter` would mitigate this.

**Comment by roderickhsiao** [comment]
Wondering should we default `quarter` off to be the same as the previous react-intl component's behavior? Cause most of people landed using this utils probably is migrating `react-intl` FormatRelative and didn't expect quarter logic

**Comment by longlho** [comment]
yeah I'm down w/ that. In the future the unit set will expand to account for things like `last Sunday`, `2 Sundays ago`...
