### ISSUE TITLE
Regex syntax error in Firefox

### ISSUE THREAD

**Issue by joelshepherd** [formatjs/formatjs-old#141]
**Which package?**
`intl-messageformat-parser`

**Describe the bug**
The regex from the `printEscapedMessage()` function causes a syntax error in Firefox.

**To Reproduce**
1. Open Firefox dev console
2. Paste in the regex from the function `/([{}](?:.*[{}])?)/su`
3. See the following error: `SyntaxError: invalid regular expression flag s`

**Screenshots**
![image](https://user-images.githubusercontent.com/4484306/62534003-5ce53180-b88b-11e9-9b91-67d02df76503.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Firefox 69.0b10

**Additional context**
While MDN lists `s` as a modifier [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), it does not list it in the error page for the syntax error [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default).

Specifically I was trying to use `<FormattedRelativeTime />` in `react-intl@3`.

Thanks!

**Comment by nstepien** [comment]
This is also an issue in IE11.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap

**Comment by longlho** [comment]
Can you clarify your setup? `printEscapedMessage` is only used in `babel-plugin-react-intl` & tests which are not supposed to run on browsers

**Comment by nstepien** [comment]
https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat-parser/src/printer.ts#L55
https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat-parser/src/index.ts#L6

The `index` file imports the `printer` file, so it still gets included in the webpack bundle.
This function might be tree-shaken in a prod build, but it does break in dev mode in IE at least.

I'd suggest moving test code outside of non-test files.

**Comment by longlho** [comment]
oh tks a lot for the clarifications!

**Comment by joelshepherd** [comment]
I can confirm with @MayhemYDG's find. It is only present in my local dev build running webpack dev server and stopping the js parsing. It is not present in my production builds and everything works normally.

**Comment by longlho** [comment]
fixed in 0c34ee46f87459853ceef3a92309e77a5dd4b82c

**Comment by nstepien** [comment]
I'm getting these webpack errors now after the update:
```
ERROR in ./node_modules/intl-messageformat-parser/dist/index.mjs 8:8-32
Can't import the named export 'normalizeHashtagInPlural' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/format.js
 @ ./node_modules/react-intl/dist/components/message.js
 @ ./node_modules/react-intl/dist/index.js
...

ERROR in ./node_modules/intl-messageformat-parser/dist/index.mjs 6:14-22
Can't import the named export 'parse' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/format.js
 @ ./node_modules/react-intl/dist/components/message.js
 @ ./node_modules/react-intl/dist/index.js
...
```

**Comment by longlho** [comment]
can u try `react-intl@3.1`?

**Comment by nstepien** [comment]
I'm already on reac-intl@3.1, from my lockfile:
```
    "react-intl": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/react-intl/-/react-intl-3.1.0.tgz",
      "integrity": "sha512-3KV+iqnBui7//JCsyegCfWcI4+anMU8bR2FLhbau/rKMeh7JxtugreMv2Nd4YNSNITh7XFyJmPk/1GZ//mvc3A==",
      "requires": {
```

**Comment by longlho** [comment]
would u mind creating a sample repo of ur config? e.g: https://codesandbox.io/s/nervous-shirley-i333t seems to be ok

**Comment by nstepien** [comment]
I'll see later if I can create a sample repo.
For now I've added `.mjs` before `.js` in webpack's `resolve.extensions` config, but it doesn't help much:
```
ERROR in ./node_modules/react-intl/dist/components/message.mjs 33:46-61
Can't import the named export 'Component' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

ERROR in ./node_modules/react-intl/dist/utils.mjs 55:17-31
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

ERROR in ./node_modules/react-intl/dist/components/message.mjs 60:28-42
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

ERROR in ./node_modules/react-intl/dist/components/relative.mjs 77:51-70
Can't import the named export 'PureComponent' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

ERROR in ./node_modules/react-intl/dist/components/provider.mjs 14:42-61
Can't import the named export 'PureComponent' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

ERROR in ./node_modules/react-intl/dist/components/injectIntl.mjs 15:20-39
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
 @ ./node_modules/react-intl/dist/index.mjs

......
```
It's failing to import React stuff.
I think mjs files can only import from other ES modules/mjs files? So we'd need to use require to use React in those files?

**Comment by MayhemYDG** [comment]
https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field

>import statements of .js and extensionless files are treated as ES modules if the nearest parent package.json contains "type": "module".

**Comment by longlho** [comment]
yeah so `react-intl` & its packages have the correct setup https://github.com/formatjs/react-intl/blob/master/package.json#L33-L35 I'm confused since other bundlers seem to work (rollup/parcel).

Googling around this seems to pop up to add to webpack config?
```
{
    test: /\.mjs$/,
    type: 'javascript/auto',
},
```

**Comment by nstepien** [comment]
I'll give this a try later, thanks.

**Comment by longlho** [comment]
I'm combining this w/ #143
