### ISSUE TITLE
RelativeTimeFormat locale-data bundles the polyfill itself

### ISSUE THREAD

**Issue by ephys** [formatjs/formatjs-old#142]
**Which package?**

`@formatjs/intl-relativetimeformat@2.5.0`

**Describe the bug**

When bundles for browsers using eg webpack, attempting to lazy-load locale-data from this package will also load a duplicated version of `@formatjs/intl-relativetimeformat/index.js` (which includes core.js + en locale).

This is because every file in `/dist/locale-data/` [starts with an import of `index.js`](https://github.com/formatjs/formatjs/blob/c012d6e67cf70e5ef23d7bf2573d4102b3035cb9/packages/intl-relativetimeformat/scripts/cldr.js#L34)

I thought of only loading locale-data but then the polyfill isn't actually installed because `polyfill.js` is not loaded

**To Reproduce**

1. Bundle the following code using webpack:

```
await import('@formatjs/intl-relativetimeformat/polyfill');
await import('@formatjs/intl-relativetimeformat/dist/locale-data/de');
```

2. Look at the resulting bundle files, the one for the `de` locale data also contains the polyfill & the `en` locale-data.

**Expected behavior**

the webpack chunk containing the `locale-data/de` file only contains the locale data & a call to insert it, but not core.js nor locale-data/en

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] N/A

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] N/A
- OS: [e.g. iOS8.1] N/A
- Browser [e.g. stock browser, safari] N/A
- Version [e.g. 22] N/A

**Additional context**

**Comment by longlho** [comment]
fixed in 394660032857455cfab0d15312d817107e124977
