### ISSUE TITLE
Problems after change to .mjs files

### ISSUE THREAD

**Issue by mvestergaard** [formatjs/formatjs-old#143]
In reference to commit 0c34ee46f87459853ceef3a92309e77a5dd4b82c

This is causing issues. I don't know if it was intentional for the package to contain both .js and .mjs files, but it seems to cause confusion.

This is what the dist folder of the package contains
![image](https://user-images.githubusercontent.com/2027834/62552707-644a1200-b86e-11e9-9610-fb9db82d226b.png)

And it's causing these types of errors:
![image](https://user-images.githubusercontent.com/2027834/62552735-6f9d3d80-b86e-11e9-804d-068a24e150d9.png)

For some reason these imports seem to use the .js files over the .mjs files
![image](https://user-images.githubusercontent.com/2027834/62552849-99566480-b86e-11e9-8224-b0bdffbd7fcd.png)

Node 12.5.0
Webpack 4.39.1
Babel 7.5.4

**Comment by longlho** [comment]
Would u mind creating a sample reproducible setup (https://codesandbox.io or something). Our build uses rollup and everything seems fine so I'm having a hard time tracking this down.

**Comment by mvestergaard** [comment]
I can try, but I'm heading home from the office in a sec.

I'm wondering whether it may be due to `react-intl` using `3.0.1` of the package while `intl-messageformat` and `babel-plugin-react-intl` use `3.0.2`. I don't see that yarn installed it in both versions though, so that may not be it.

**Comment by longlho** [comment]
can u try `react-intl@3.1`?

**Comment by mvestergaard** [comment]
Same thing. I tried reinstalling all node_modules too, same result.

**Comment by mvestergaard** [comment]
I created a bare bones create-react-app project and installed the latest react-intl.
I get similar issues there, but with react-intl itself rather than intl-messageformat-parser

![image](https://user-images.githubusercontent.com/2027834/62556099-7d55c180-b874-11e9-8cab-0d6184dd0a94.png)

**Comment by longlho** [comment]
u mind pushing it somewhere I can debug? Thanks!

**Comment by mvestergaard** [comment]
Here you go https://github.com/mvestergaard/react-intl-repro

**Comment by asual** [comment]
The following workaround seems to resolve the issue for me:
https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022

**Comment by longlho** [comment]
Yeah this seems to be an issue within CRA itself instead of individual bundler (rollup/webpack/babel/parcel...)

**Comment by mvestergaard** [comment]
Well the app where i have the problem doesn't use CRA, that was only the repro.

**Comment by longlho** [comment]
let me try w/ vanilla webpack

**Comment by asual** [comment]
I also don't use CRA but plain Webpack with ts-loader.

**Comment by longlho** [comment]
https://github.com/mvestergaard/react-intl-repro/pull/1 does this solve it?

**Comment by longlho** [comment]
```
{
            test: /\.mjs$/,
            type: 'javascript/auto',
        },
```
seems to do the trick

**Comment by mvestergaard** [comment]
It does, thanks.

I'm kinda thinking it shouldn't be necessary, but that may be more of a webpack complaint.

**Comment by longlho** [comment]
the interop between ESM & CJS is a mess unfortunately :(

**Comment by nstepien** [comment]
Okay so this is good enough to get it bundled in webpack:
```js
module.rules = [{
  test: /\.mjs$/,
  type: 'javascript/auto'
}]
```

but you also need to tell webpack to resolve mjs files before js files, in case you had overwritten the default setting:
```js
resolve.extensions = ['.ts', '.tsx', '.mjs', '.js'];
```
otherwise you end up with commonjs files bundled in, which isn't optimal.

**Comment by longlho** [comment]
thanks a lot @MayhemYDG !

**Comment by nstepien** [comment]
One more thing, especially for users that need to support IE, if you use `.babelrc` instead of `babel.config.js`, babel-loader will not transpile files under `node_modules`, so you need to change your babel config filename.
https://babeljs.io/docs/en/configuration
https://babeljs.io/docs/en/config-files

**Comment by longlho** [comment]
For tracing purposes: https://github.com/facebook/create-react-app/issues/4317
