### ISSUE TITLE
Unable to import intl-messageformat since version 6.0.3

### ISSUE THREAD

**Issue by tirithen** [formatjs/formatjs-old#144]
**Which package?**
intl-messageformat

**Describe the bug**
Unable to use `import IntlMessageFormat from 'intl-messageformat';` with webpack/babel after upgrade from 6.0.1 to 6.0.3. Should have been marked as a major release instead?

This is the errors I get in the build log:
```
ERROR in ./node_modules/intl-messageformat-parser/dist/index.mjs 8:8-32
Can't import the named export 'normalizeHashtagInPlural' from non EcmaScript module (only default export is available)
 @ ./node_modules/intl-messageformat/dist/index.js
 @ ./utils/Localizer.js
 @ ./shared/appData/index.js
 @ ./shared/index.js

ERROR in ./node_modules/intl-messageformat-parser/dist/index.mjs 6:14-22
Can't import the named export 'parse' from non EcmaScript module (only default export is available)
 @ ./node_modules/intl-messageformat/dist/index.js
 @ ./utils/Localizer.js
 @ ./shared/appData/index.js
 @ ./shared/index.js
```

**To Reproduce**
1. Setup a project with webpack/babel
2. Add intl-messageformat dependency
3. Create a js file with `import IntlMessageFormat from 'intl-messageformat';`
4. Build with webpack

**Expected behavior**
Should be possible to import the package

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser N/A (problem is build releated) 
- Version 6.0.3 (intl-messageformat-parser 3.0.1 got installed automatically as well)

**Comment by tirithen** [comment]
Possibly related to https://github.com/formatjs/formatjs/issues/143 ?

**Comment by tirithen** [comment]
Also possibly related to https://github.com/formatjs/formatjs/issues/141#issuecomment-518723661 ?

**Comment by longlho** [comment]
#143 	should have the workaround so I'm closing as duplicate. Thanks for reporting.
