### ISSUE TITLE
Plural hashtag token normalization issue in nested elements

### ISSUE THREAD

**Issue by rubycon** [formatjs/formatjs-old#145]
**Which package?**
`intl-messageformat-parser`

**Describe the bug**
Plural hashtag tokens are not normalized to numbers when a plural form is nested in another element option (e.g. select).

The normalization function return early if the current element isn't a `PluralElement`, thus preventing the normalizer to process nested element (or options of other elements, such as `SelectElement`)

The early return should check for other elements with options: 
```js
if (!isPluralElement(el) && !isSelectElement(el)) {
    return;
}
```

**To Reproduce**
With the following format string, for `type="drop"` and  `units=1`, I get : 
> \# drop
```
{type, select,
  drop {
    {units, plural,
      one {# drop}
      other {# drops}
    }
  }
  teaspoon {
    {units, plural,
      one {# teaspoon}
      other {# teaspoons}
    }
  }
  tablespoon {
    {units, plural,
      one {# tablespoon}
      other {# tablespoons}
    }
  }
}
```
**Expected behavior**
I should get : 
> 1 drop

**Comment by longlho** [comment]
Thanks for reporting. We'll fix this asap
