### ISSUE TITLE
Invalid regular expression flag "s" on Firefox

### ISSUE THREAD

**Issue by eliseumds** [formatjs/formatjs-old#147]
**Which package?**

intl-messageformat-parser at https://github.com/formatjs/formatjs/blob/b6ea222370f51e2cb86c6da2357008783767e8c4/packages/intl-messageformat-parser/src/printer.ts#L56

**Describe the bug**

The RegEx flag `s` is apparently not supported by Firefox

**To Reproduce**

Just paste `/([{}](?:.*[{}])?)/su` in Firefox's console and hit Enter. You'll get `SyntaxError: invalid regular expression flag s` with a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag

Firefox 68.0.1 on MacOS Mojave

**Comment by longlho** [comment]
What version are you using?

**Comment by eliseumds** [comment]
@longlho ops, sorry. I was using `intl-message-format@6.0.1`

Funnily, I just reinstalled it and my build started breaking with:

```
 error  in /Users/eliseumds/war/git/productreview/node_modules/intl-messageformat-parser/dist/index.mjs

Can't import the named export 'normalizeHashtagInPlural' from non EcmaScript module (only default export is available)

 error  in /Users/eliseumds/war/git/productreview/node_modules/intl-messageformat-parser/dist/index.mjs

Can't import the named export 'parse' from non EcmaScript module (only default export is available)
```

Ah, makes sense, `intl-messageformat-parser` is listed as a dependency but [the version is not locked/exact](https://github.com/formatjs/formatjs/blob/6e67775d81ba150bf565c9b49ffee06b48fddbcb/packages/intl-messageformat/package.json#L35), so it reinstalled it with the latest.

**Comment by longlho** [comment]
oh u might need to tweak ur webpack config: https://github.com/formatjs/formatjs/issues/143#issuecomment-518774786

**Comment by mulholo** [comment]
Can we please reopen this? Tweaking the webpack config didn't fix this for me

**Comment by longlho** [comment]
did u upgrade to latest version?

**Comment by mulholo** [comment]
Yes, using `intl-messageformat-parser@3.0.7` via `react-intl@3.1.9`

**Comment by longlho** [comment]
what's the output of `npm ls intl-messageformat-parser`?

**Comment by mulholo** [comment]
```
web_client@1.0.0 /opt/web_client
+-- babel-plugin-react-intl@4.1.12
| `-- intl-messageformat-parser@3.0.7
`-- react-intl@3.1.9
  +-- intl-messageformat@6.1.9
  | `-- intl-messageformat-parser@3.0.7  deduped
  `-- intl-messageformat-parser@3.0.7  deduped
```

**Comment by longlho** [comment]
hmm that looks right. Do u have a sample repro repo?

**Comment by David263** [comment]
I'm getting "SyntaxError: invalid regular expression flag s" in the latest 2019 Firefox, 68.0.2 and 69.0.

**Comment by longlho** [comment]
Are you on latest versions of stuff?

**Comment by RafaelLiendo** [comment]
v69.0.1 on windows, same problem

**Comment by kshetline** [comment]
I've got the same bug with Firefox 69.0.1 (64-bit) on MacOS 10.14.6.

It's as simple as entering `/.+/s.test('\n')` into the console. This fails on Firefox with "SyntaxError: invalid regular expression flag s". Doesn't have anything to do with `intl-messageformat-parser` or webpack. The regex *fails in the console*.

Works fine on Chrome and Safari.

**Comment by niran-manandhar** [comment]
any suggestions?

**Comment by David263** [comment]
@niran-manandhar and others: there is a bug report on this problem in the Mozilla database that I have been following, and the bug has recently been fixed. The fix should appear in a release very soon. The reason for the long delay was that some tricky programming needed to be done to incorporate the latest feature support for a recently added group of standard JavaScript features that included the "s" flag. I'm just reporting what's in the bug report; I didn't do the work.
