### ISSUE TITLE
intl-messageformat: `Malformed XML message ` for non rich text

### ISSUE THREAD

**Issue by HollyPony** [formatjs/formatjs-old#148]
### Expected behavior

translations messages using `<` sign (probably `>` too) should be render without errors

### Current behavior

translations messages using `<` sign trigger a `Malformed XML message ` in console

### Step to reproduce for BUG REPORT

```
messages: {
  returnToList: `< back to list of items`
}

...

useIntl().formatMessage({ id: 'returnToList'})
```

https://codesandbox.io/s/githubcomformatjsformatjsissue148-k4u95

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.10.3 |
|    `node --version` | 12.8.0 |

| OS   | Version |
| ---- | ------- |
| OSX | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| chrome    | 76 |

### Proposal

If there it's possible : document the part to achieve this.

It's useful to `rtl` texts

Add a `rich` parameter to formatMessage or add a `formatSimpleMessage` / `formatRichMessage` function.

Depending if you prefer solve the break between `v2` and `v3` or `v3.1` and `v3.2`

EDIT: Seems related to :

- https://github.com/formatjs/react-intl/blob/master/src/format.ts#L317
- https://github.com/formatjs/react-intl/blob/master/src/format.ts#L352

Additionally I wan't to point the fact `formatXmlMessage` fallback to a simple format message so the render is good. The bug is the annoying `console.error` message

**Comment by longlho** [comment]
~@HollyPony I think `&lt;` is preserved in latest version now. Can u give that a try?~ sry I lied, looks like it's still emitting errors

**Comment by HollyPony** [comment]
As far I can see in the codesandbox test cas, `&lt;` doesn't trigger error but is display as is 🤷‍♂

**Comment by longlho** [comment]
The workaround is to separate out as icon unfortunately. `<` isn't safe in bidi context. I'll try to figure out a fix soon

**Comment by HollyPony** [comment]
There is no way to let the user option if the text should be xml parsed ? It could also be a performance issue imo

**Comment by longlho** [comment]
That can be added to the component yeah

**Comment by HollyPony** [comment]
FYI: I found a temporary quick ugly fix :

```
messages: {
  returnToList: `{lt} back to list of items`
}

useIntl().formatMessage({ id: 'returnToList'}, {
  lt: <span>{'<'}</span>
})
```

codesandbox sample also updated.

**Comment by GianfrancoCorrea** [comment]
im geting this error because "rsquo;"

![image](https://user-images.githubusercontent.com/46355516/63431917-6081c800-c3f6-11e9-908c-ea5efa02c5a6.png)

also i got "[React Intl] Cannot format message: "kognitiv.terms_of_use", using message source as fallback."

**Comment by longlho** [comment]
can u try latest @GianfrancoCorrea  ?

**Comment by GianfrancoCorrea** [comment]
@longlho i just tried with 3.1.11, and got same error.

The only way to view the formatted message is puting a `<Formattedmessage />` under intl.formatMessage's **defaultMessage**:

![image](https://user-images.githubusercontent.com/46355516/63458179-ace5fb80-c428-11e9-8f85-0df1ef5b90f1.png)

and it work but with another new error message:

![image](https://user-images.githubusercontent.com/46355516/63458327-01897680-c429-11e9-894a-189b3235e944.png)

**Comment by longlho** [comment]
hmm any reason why you're not using `FormattedHTMLMessage`? the output of `formatMessage` is not safe for `dangerouslySetInnerHTML` consumption

**Comment by GianfrancoCorrea** [comment]
No reason, I'm just testing possibilities, with `FormattedHTMLMessage` i got same "Malformed XML message" error

**Comment by longlho** [comment]
sry i'm lost. Would u mind putting up a codesandbox?

**Comment by GianfrancoCorrea** [comment]
in this example is working with the three errors
codesandbox: https://codesandbox.io/s/githubcomformatjsformatjsissue148-2buvk
