### ISSUE TITLE
Not possible to use empty strings in `values` object

### ISSUE THREAD

**Issue by ipanasenko** [formatjs/formatjs-old#156]
### Expected behavior

Should render empty string

### Current behavior

Renders timestamp and id (I guess)

### Step to reproduce for BUG REPORT

Example here:
https://codesandbox.io/s/nice-hypatia-jue2m

**Comment by longlho** [comment]
`intl-messageformat@6.1.6` has the fix

**Comment by ipanasenko** [comment]
You probably should update version of intl-measageformat in package.json and release new version of react-intl. Lock files won't update it automatically

**Comment by longlho** [comment]
yup will do. I'm getting some other fixes in over there.
