### ISSUE TITLE
Intl.RelativeTimeFormat.supportedLocalesOf return true even if locale-data is not loaded

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs-old#157]
**Which package?**
intl-relativetimeformat

**Describe the bug**
https://github.com/formatjs/react-intl/issues/1429#issuecomment-522046952

**To Reproduce**
1. Load `RelativeTimeFormat` polyfill
1. Use function `supportedLocalesOf` to test locale
1. It returns true even the `locale-data` hasn't been loaded. 

**Expected behavior**
Should return false 

**Additional context**

**Comment by roderickhsiao** [comment]
⚡️ ⚡️ ⚡️ ⚡️ ⚡️

**Comment by longlho** [comment]
`2.6.4` should have the fix.

**Comment by roderickhsiao** [comment]
Tested, working perfectly now.
