### ISSUE TITLE
Compiled intl-unified-numberformat

### ISSUE THREAD

**Issue by klimashkin** [formatjs/formatjs-old#159]
Thank you for the intl-unified-numberformat!

Is it possible to put compiled version into npm package?

**Comment by longlho** [comment]
By compiled you mean like UMD rollup’ed output?

**Comment by klimashkin** [comment]
@longlho thanks for the commit! But I still can't see UMD version in the npm package

<img width="670" alt="Screen Shot 2019-08-28 at 7 03 05 PM" src="https://user-images.githubusercontent.com/576077/63904611-7f6bf580-c9c6-11e9-9ddd-5c258cf2c749.png">

**Comment by longlho** [comment]
ok that should be fixed in `0.4.3` now https://unpkg.com/@formatjs/intl-unified-numberformat@0.4.3/dist/umd/intl-unified-numberformat.min.js
