### ISSUE TITLE
React Intl babel plugin compatibility with v3

### ISSUE THREAD

**Issue by Betree** [formatjs/formatjs-old#160]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
I'm trying to update to https://github.com/formatjs/react-intl V3. `babel-plugin-react-intl` seems mostly compatible with it but I encounter one issue related to the fact that escaping brackets [is now done with apostrophes](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#escape-character-has-been-changed-to-apostrophe-):

```tsx
// Before
<FormattedMessage defaultMessage="\\{foo\\}" /> //prints out "{foo}"

// After
<FormattedMessage defaultMessage="'{foo}'" /> //prints out "{foo}"
```

When I do: `A quoted value ''{value}'`
babel-plugin-react-intl extracts it as: `A quoted value '{value}'` 

Which turns out in `{value}` not being replaced by the correct counterpart.

**To Reproduce / Expected behavior**

```tsx
// Should render -> A quoted value '42'
<FormattedMessage 
    id="my_id" 
    defaultMessage="'A quoted value ''{value}'" 
    values={{ value: 42 }} 
/> 
```

Should produce:

```json
{
    "my_id": "A quoted value ''{value}'"
}
```

**Comment by longlho** [comment]
Ah this looks like a bug in our printer, cc @pyrocat101

**Comment by longlho** [comment]
@Betree can u try master?

**Comment by Betree** [comment]
@longlho It works! https://github.com/formatjs/formatjs/commit/6897ca91e251ed850467ccef5794eec0999ef95b is a great change for us, by changing the string formats `4.1.13` was resetting a lof of translations in our system (see https://circleci.com/gh/opencollective/opencollective-frontend/38462). Now it only changes 3 (because strings are not trimmed anymore, which is great too).

Thank you so much for this quick fix, looking forward for the release!

Ps: if formatjs ever want to join https://opencollective.com, Open Collective's engineers would be happy to contribute financially to the project. I've personally pledged to contribute on https://opencollective.com/formatjs

**Comment by longlho** [comment]
`4.1.14` should have it. Thanks for the offer I really appreciate it 💯 Personally I'm trying to convince Dropbox to dedicate resources to this but I'll think about it!
