### ISSUE TITLE
Message descriptor without a default message

### ISSUE THREAD

**Issue by bensampaio** [formatjs/formatjs-old#162]
**Which package?**
babel-plugin-react-intl

**Is your feature request related to a problem? Please describe.**
In the type definitions of `react-intl` I see that the `defaultMessage` property of a `MessageDescriptor` is optional. This is also the case in the [documentation of defineMessages](https://github.com/formatjs/react-intl/blob/master/docs/API.md#definemessages). However, if I try to remove the `defaultMessage` property from any descriptor then `babel-plugin-react-intl` gives the follwoing error: `Message Descriptors require an 'id' and 'defaultMessage'`.

**Describe the solution you'd like**
I would like to be able to define my messages using ids only. I have no use for default messages. They only make the bundles bigger and bigger. Besides that, in my application I want to show text to the user only when the correct language is determined. However, since my default messages are in English users always see text in English before it changes to their preferred language. This doesn't take a long time but it is annoying for users.

**Describe alternatives you've considered**
An alternative would be to avoid rendering translations until the language is determined but I still didn't find an easy and maintainable way of doing this.

**Comment by longlho** [comment]
Did u try setting `enforceDefaultMessage: false` in `babel-plugin-react-intl`?

**Comment by bensampaio** [comment]
That seems to work, thanks :)

Now the problem is on the formatting functions. On first render they log an error to the console because a `defaultMessage` can't be found. Besides that,  they render the id as a fallback while I expected an empty string. Do I have to always set an empty `defaultMessage` to make sure that it is rendered instead of the id? Or is there another way around this problem?

**Comment by longlho** [comment]
What’s the specific error message?

**Comment by bensampaio** [comment]
@longlho  this is the error message I get: `[React Intl] Cannot format message: "forgotPasswordScreen.heading", using message id as fallback.`

**Comment by longlho** [comment]
ah kk yeah that's expected then :)

**Comment by bensampaio** [comment]
I just noticed that if I set the `defaultMessage` to an empty string then I still get the error above and also this one: `[React Intl] Missing message: "forgotPasswordScreen.heading" for locale: "en"`.

If the type definitions specify that the `defaultMessage` is optional why are these errors being thrown? Shouldn't this be configurable?

**Comment by longlho** [comment]
it's hard to tell without seeing your setup. The lookup hierarchy is that we look at the ID in the `messages` table, if nothing's there we try to format `defaultMessage`, if nothing's there then we just render out the ID.

The `Missing message` is probably bc you pass in `messages` that don't have that ID.

**Comment by bensampaio** [comment]
Yeah, I get it now. Since I don't want default messages I just made sure that the messages for a locale are fetched before rendering. My CI already makes sure there is always a translation for every id so in this way my app never needs to fallback on default messages.

Thank you for your help!
