### ISSUE TITLE
Special characters in select keys throw in 3.0.0, was fine in 2.1.x and before

### ISSUE THREAD

**Issue by jcestibariz** [formatjs/formatjs-old#164]
**Which package?**
intl-messageformat-parser

**Describe the bug**
If a key in a select block contains special characters, like `-` or `/`, parse throws `SyntaxError: Expected argName but "/" found.`

**To Reproduce**

1. Run this in node:
    ```js
    const parser = require('intl-messageformat-parser');
    parser.parse('{x, select, /a-key {Result}}');
    ```
2. With intl-messageformat-parser@2.1.3 and below it passes
3. With intl-messageformat-parser@3.0.0 and above it fails

**Expected behavior**
The message should be parsed without errors.

**Comment by longlho** [comment]
Yeah this is intentional since our parser behaves more closely with ICU messageformat spec now (which excludes special char from placeholder)
