### ISSUE TITLE
Pluralization silently accepts duplicate categories

### ISSUE THREAD

**Issue by nbouvrette** [formatjs/formatjs-old#168]
**Which package?**
https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat-parser

**Describe the bug**
When trying to parse a message which contains duplicate plural categories, the parser takes the last one only and silently ignore duplicate categories.

**To Reproduce**

1. Run this code:

```javascript
var testString = 'You have {count, plural, one {# hot dog} one {# hamburger} one {# sandwich} other {# snacks}} in your lunch bag.';
import {parse} from 'intl-messageformat-parser';
const ast = parse(testString);
console.dir(testString);
```

2. You will see that only the "sandwhich" plural category remains in the AST.

**Expected behavior**
If the markup is invalid, an exception should be thrown.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**

- OS: Tested on OSX.
- Browser: Tested in the latest version of Chrome
- Version: Latest 

**Smartphone (please complete the following information):**

- Device: Not tested
- OS: Not tested
- Browser Not tested
- Version Not tested

**Additional context**
No additional context.

**Comment by nbouvrette** [comment]
Would it be possible to know why this issue was closed?

**Comment by longlho** [comment]
Latest version has the fix :)

**Comment by nbouvrette** [comment]
Yes thanks - wrote my comment too fast! I will update my version right away!
