### ISSUE TITLE
Sub-tags are not supported in messages

### ISSUE THREAD

**Issue by tonnyavery** [formatjs/formatjs-old#176]
I am trying to display a very simple string:
`<pm>Personal license code: <strong>{licenseCode}</strong><pm>`
Outermost `<pm>` should transform into my custom styled component
Inner `<strong>` should become a bold entry

Even with new Rich Text support, looks like only first level of tags in messages is being parsed.
So I end up with `<pm>` working, but `<strong>` not

**Comment by nbouvrette** [comment]
I just did a quick test and could not reproduce - could you provide more details?

```js
console.log((new IntlMessageFormat.IntlMessageFormat('<pm>Personal license code: <strong>{licenseCode}</strong><pm>', 'en')).format({licenseCode: 'ABC123'}));
```

Output:
```
<pm>Personal license code: <strong>ABC123</strong><pm>
```

**Comment by tonnyavery** [comment]
@nbouvrette hmm
I am using it as a part of `react-intl` package.
There if I have
```
intl.formatMessage({
  { id: 'none', defaultMessage: '<pm>Personal license code: <strong>{licenseCode}</strong><pm>' }, {
  ps: msg => <PS>{msg}</PS>,
        pm: msg => <PM>{msg}</PM>,
        strong: msg => <strong>{msg}</strong>
}
}, formattingProps)
```

I end up without `<strong>`

If I change to 
```
pm: msg => { console.log(msg); return <PM>{msg}</PM> }
```
I can see in the logs that `msg` doesn't have `<strong>` in it already

**Comment by tonnyavery** [comment]
Should I move this ticket to react-intl repo? I have probably created it here by mistake

**Comment by longlho** [comment]
Nope this is the correct repo

**Comment by tonnyavery** [comment]
Ok, then I'll just give you a more detailed example, because I think it highlights another big flaw in react-intl – lack of support for arrays or consecutive entries.

So I have a section on the website, let's say FAQ on a landing.
I need 3 entries of
```
<h3>faq 1 title<h3>
<pm>faq text</pm>
```
where every entry is a custom styled component

Here is what I now have in the localization file:
```
'index.faq': [
    '<h3>FAQ . 1?</h3>',
    '<pm>Text1</pm>',
    '<h3>FAQ 2</h3>',
    '<pm>Text2<tutorials>Tutorials</tutorials></pm>',
    '<h3>FAQ 3?</h3>',
    '<pm>Text 3 <free>FREE</free></pm>',
    '<readfaq>Read FAQ</readfaq>'
  ],
```
And this is what I end up doing to handle it:
```
export default injectIntl(({ intl }) => {
  const { locale } = intl
  const printMessage = message => {
    const formattingProps = {
      h3: msg => <H3>{msg}</H3>,
      pm: msg => <PM>{msg}</PM>,
      free: msg => { special free handling with link},
      tutorials: msg => { special tutorials handling with link},
      readfaq: msg => (
        <BlueButton
          onClick={() => {
            ...
          }}
        >
          {msg}
        </BlueButton>
      )
    }

    return intl.formatMessage(
      {
        id: 'none',
        defaultMessage: message
      },
      formattingProps
    )
  }

  return (
    <LandingRow>
      <LandingRowContent>
        <H2>
          <FormattedHTMLMessage id='faq' />
        </H2>
        {intl.messages['index.faq'].map(printMessage)}
      </LandingRowContent>
    </LandingRow>
  )
})
```
And now the problem is that all inner custom tags that I have do not work

**Comment by longlho** [comment]
@AAverin can u try latest master for `intl-messageformat`?

**Comment by tonnyavery** [comment]
@longlho With exact setup I had, on the latest version I don't get any text at all. Not the text inside my inner-tag, and no text after that tag in the same localization entry.
I will keep testing

**Comment by tonnyavery** [comment]
Having
`'test.test': '<pm>Test1<free>Free</free>Test2</pm>',`
and 
`<FormattedMessage id='test.test' />`

Without any values passed into FormattedMessage, I get the output of:
`<pm>Test1<free>Free</free>Test2</pm>`

If I pass replacement for inner-tag:
```
<FormattedMessage id='test.test' values={{
            free: msg => <strong>{msg}</strong>
          }} />
```

I get the output of 
`<pm>Test1<free>Free</free>Test2</pm>`
So inner tag was not replaced

If I pass the replacement for outer tag
```
<FormattedMessage id='test.test' values={{
            pm: msg => <i>{msg}</i>
          }} />
```
, I get output of italic `Test1`.
So only the first part was processed and inner tag with all text after it was ignored

If I pass replacements for both inner and outer tags
```
<FormattedMessage id='test.test' values={{
            free: msg => <strong>{msg}</strong>,
            pm: msg => <i>{msg}</i>
          }} />
```
 I get output of italic `Test1`, so same problem, inner-tag was ignored and all text after it too

**Comment by tonnyavery** [comment]
Ok, looks like it's no longer just message, but chunks.
Works with 
```
<FormattedMessage id='test.test' values={{
            free: (...msg) => <strong>{msg}</strong>,
            pm: (...msg) => <i>{msg}</i>
          }} />
```
Will try a larger example

**Comment by tonnyavery** [comment]
Yes, all good now.
Thanks for a quick fix

**Comment by tonnyavery** [comment]
@longlho small regression, probably?
`<br />` doesn't seem to work within custom tags, even though according to https://github.com/formatjs/react-intl/issues/1458 it is supported

**Comment by tonnyavery** [comment]
I tried in your sandbox on that issue, and on 3.1.3 inner `<br/>` works fine, but when I update to 3.2.1 it doesn't

**Comment by longlho** [comment]
@AAverin can u try latest `intl-messageformat`?

**Comment by tonnyavery** [comment]
Sure. I have workedaround with a custom placeholder for now
