### ISSUE TITLE
Messages are not collected from react-intl components in node_modules

### ISSUE THREAD

**Issue by jahglow** [formatjs/formatjs-old#177]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
React-intl messages are not extracted from external react components published via npm and residing in node_modules in the project the babel plugin is used in.

**To Reproduce**
Say I have created a reusable React Component 'HelloWorld' which is published as an npm-repo :
messages.js:
```js
import {defineMessages} from 'react-intl'

export default defineMessages({
  pageTitle: {
    id: 'helloWorld.pageTitle',
    defaultMessage: 'Hello world!',
  }
})
```

index.js:
```js
import {IntlProvider, useIntl} from 'react-intl';
import messages from './messages';
export {default as messages} from './messages';

export default function HelloWorld(){
  const {formatMessage} = useIntl();
  return <H1>{formatMessage(messages.pageTitle)}</H1>
}
```

Then this component is used in an app:
```js
import {IntlProvider, useIntl} from 'react-intl';
import HelloWorld, {messages as helloWorldMessages} from 'hello-world-npm'; //importing messages doens't help
import translations from './translations/i18n'; //these are translations collected from local app modules via this babel plugin

const App= ()=>{
  const {formatMessage} = useIntl();
  return <H1>{formatMessage(messages.pageTitle)}</H1>
}

ReactDOM.render(
  <IntlProvider locale={'en'} messages={translations}>
    <App />
  </IntlProvider>,
  document.getElementById('container')
);
```

./translations/i18n.js
```js
const enTranslationMessages = require('./locales/en.json');
const ruTranslationMessages = require('./locales/ru.json');

export const appLocales = ['en', 'ru'];

export const formatTranslationMessages = messages =>
  Object.entries(messages || {}).reduce(
    (acc, [id, message, defaultMessage]) => Object.assign({}, acc, {[id]: message || defaultMessage}),
    {}
  );

export const translationMessages = {
  en: formatTranslationMessages(enTranslationMessages),
  ru: formatTranslationMessages(ruTranslationMessages),
};

```

these localse are bundled into translations via this script:
```js
const manageTranslations = require('react-intl-translations-manager').default;

manageTranslations({
  messagesDirectory: 'src/translations/extracted',
  translationsDirectory: 'src/translations/locales/',
  languages: ['ru', 'en'],
});
```

 The problem:
Babel plugin *doesn't collect* messages from node_modules, i.e. 'hello-world-npm' module, only from local files (`./src` folder), and as a result the messages don't appear in `extracted` folder hierarchy and do not end up in `locales` as a consequence

**Expected behavior**
All translations should be collected from all files used in the project including the node_modules ones

**Screenshots**

**Additional context**

**Comment by longlho** [comment]
https://github.com/formatjs/formatjs/issues/65#issuecomment-529453254

> Yeah it does not collect from node_modules. What Yahoo and DBX do is every package aggregates its strings into a file, e.g lang/strings_en-US.json and they get merged upstream by the consumer, following the dependency tree declared in package.json.

**Comment by jahglow** [comment]
can you please suggest how to `get them merged upstream by the consumer, following the dependency tree declared in package.json`? I don't quite understand the process...

**Comment by longlho** [comment]
You can declare your translation file location in `package.json` for your packages, something like:

```
{
  "i18n": [
	"lang/strings_en-US.json",
	"lang/strings_de-DE.json"
  ]
}
```

Then during webpack build and such, look for those and aggregate them.
