### ISSUE TITLE
plural - IE 11

### ISSUE THREAD

**Issue by sapottier** [formatjs/formatjs-old#178]
**Which package?**
"intl-messageformat": "^7.2.1"

**Describe the bug**
IE11 return an error like "can't bind property 'bind' of null" it works with chrome (sorry for approximation. IE translate it in french...)

**To Reproduce**
const translation = '{itemCount, plural, =0 {no items} one {1 item} other {{itemCount} items}}'
new IntlMessageFormat(translation, local).format(variable);

the line below works
const translation = '{itemCount} items'

**Expected behavior**

**Comment by longlho** [comment]
Did you polyfill Intl.PluralRules? We have @formatjs/intl-pluralrules to
polyfill

**Comment by sapottier** [comment]
Considering documentation, I don't need it ?

> This package assumes that the Intl global object exists in the runtime. Intl is present in all modern browsers (IE11+) and Node (with full ICU). The Intl methods we rely on are:

**Comment by longlho** [comment]
The global Intl object is available in IE11 but not all Intl APIs are.

**Comment by sapottier** [comment]
My bad... Thank you it works :)  (maybe the documentation need some clarification) (sorry for my english)

**Comment by longlho** [comment]
PR to improve doc is always welcome :)
