### ISSUE TITLE
Expose Arguments Information in MessageFormat or at least the AST

### ISSUE THREAD

**Issue by vvohra** [formatjs/formatjs-old#18]
I'm wondering if it's possible to expose this in MessageFormat, so it's possible to view this runtime but re-use the intl cache to avoid creating a new Intl* object. I'm assuming parsing the AST is one of the costly parts of Intl* object constructions.

My use case (in case there's another way): I want to make a component that can pass in defaults if an argument isn't passed.

Similar to #139.

**Comment by longlho** [comment]
closed via 3d6c28904125f74c6e4c15d45eb53ebc1499caca
