### ISSUE TITLE
Upgrading intl-messageFormat from v2 to v7 - addLocaleData

### ISSUE THREAD

**Issue by yaelz** [formatjs/formatjs-old#181]
Relevant package: intl-messageFormat

We've been trying to upgrade from v.2 to v.7 and there's an issue we aren't able to solve - adding localeData in the new version. It seems intl-messageFormat used to have a function __addLocaleData which doesn't exist anymore (well, it does exist on the new Formatters). We can't upgrade to the new version if we can't add the locale data somehow, so how can we add it?
Not really a bug, but didn't know how else to approach this.

I'd like to be able to use intl-messageFormat with localeData added.
Is it added automagically like [this issue](https://github.com/formatjs/formatjs/issues/29) suggests? Do you guys pass the localeData so it's not needed anymore?

**Comment by longlho** [comment]
We use polyfill now so you can follow the instructions on
@formatjs/intl-pluralrules

**Comment by yaelz** [comment]
Thanks for the quick response!
Isn't the polyfill only for browsers that don't have embedded Intl.X support? (according to [this](https://github.com/formatjs/formatjs/blob/master/packages/intl-pluralrules/src/fix-meta.ts#L5) it does nothing if Intl.X exists)
What if we want to add specific localeData on runtime? How do you load the localeData?

**Comment by longlho** [comment]
Yeah I’m assuming you support Safari & IE11 which don’t have
Intl.PluralRules. That was the whole purpose of locale-data. Otherwise you
don’t need it.

**Comment by yaarams** [comment]
In the past all the pluralrules were embedded in intl-messageformat and localeData was added for every locale by calling __addLocaleData(fn).

The localeData is not part of the native Intl.DateTimeFormat/Intl.NumberFormat as far as I understand... so it needs to be added in order to support plurals. 

1. We want to support browsers that doesn't need the polyfill and already has Intl.X..
2. We wish to allow users to add the localeData dynamically (so we are in need for __addLocaleData) according to the relevant locale upon runtime like so:
```
initI18n({
   asyncLocaleDataLoader: (locale) => import(`i18n-config/locale-data/${locale}`),
})
```
We see that the pluralrules formatter has __addLocaleData function, but the polyfill will call return since the browser already has its own impl (and will not enrich it with this __addLocaleData func).

**Comment by longlho** [comment]
hmm we can consider adding that to the polyfill, but can u clarify what `initI18n` does? Typically from use cases that I've seen dynamic `import()` can be used, e.g:

```ts

function polyfill () {
	const necessaryPolyfills: Promise[] = []
	if (!Intl.PluralRules) {
		necessaryPolyfills.push(import('@formatjs/intl-pluralrules/polyfill'))
		if (lang === 'de') {
			necessaryPolyfills.push(import('@formatjs/intl-pluralrules/dist/locale-data/de'))
		}
	}
	return Promise.all(necessaryPolyfills)
}
await polyfill()
```

**Comment by yaelz** [comment]
How do we use localeData without the polyfill? for browsers that have Intl.PluralRules..
Maybe we don't understand what is the purpose of local-data.. we thought it adds plural rules, also for browsers with Intl.PluralRules.

**Comment by longlho** [comment]
If browser has `Intl.PluralRules`, it has *ALL* the `locale-data` 😄  Locale data are CLDR data that gets bundled with the browser of specific versions.

Similarly, if browser has `Intl.DateTimeFormat`, it has ALL the CLDR for all locales, along with ALL IANA data for all timezones.

CLDR data does get outdated though (they release twice per year) but it's not worth the weight to polyfill + add locale data just for that.

**Comment by yaelz** [comment]
Then we really need these only for polyfills, because browsers that have `Intl.PluralRules` have all the data. Gotcha. Thanks :)
