### ISSUE TITLE
Updating formats and date custom patterns handling

### ISSUE THREAD

**Issue by yaelz** [formatjs/formatjs-old#183]
intl-messageformat

This library is missing default behaviour, plus support for specific formatting as we know exists in ICU (http://userguide.icu-project.org/formatparse/datetime).

We'd like to add a default behaviour, plus support for specific formatting as we know exists in ICU (http://userguide.icu-project.org/formatparse/datetime) :)

PR: https://github.com/formatjs/formatjs/pull/182

**Comment by longlho** [comment]
we supported a subset of skeleton in the latest version
