### ISSUE TITLE
RelativeTimeFormat add support for adding locales in ponyfill

### ISSUE THREAD

**Issue by adipascu** [formatjs/formatjs-old#201]
**Which package?**
The package is: `intl-relativetimeformat`

**Is your feature request related to a problem? Please describe.**
I want to use the ponyfill but it only has `en` support. How can I add additional languages from the `dist` folder into it?

**Describe the solution you'd like**
I should like that each language from the `dist` folder be compatible with the ponyfill pattern.

**Describe alternatives you've considered**
I am currently using this snippet:
```
delete Intl.RelativeTimeFormat;
require('@formatjs/intl-relativetimeformat/polyfill');
require('@formatjs/intl-relativetimeformat/dist/locale-data/eo');
```

**Additional context**
Right now if I use the ponyfill as is it crashes with: `No locale data has been added to IntlRelativeTimeFormat for: eo, en-US`

**Comment by longlho** [comment]
what browser/node version are you using?

Also what version of the library are you using?

Why do u need to `delete Intl.RelativeTimeFormat` btw?

**Comment by adipascu** [comment]
I am using `@formatjs/intl-relativetimeformat` version `4.1.1` on Chrome `77.0.3865.90`.

I am deleting the browser-based API to make sure the polyfill is being used, I'd prefer to use the ponyfill instead.

**Comment by longlho** [comment]
Ah kk yeah I'll have to dist out the raw json so you can add it to the ponyfill. I thought for some reason the polyfill doesn't work.
