### ISSUE TITLE
TypeError: IntlMessageFormat is not a constructor on Node

### ISSUE THREAD

**Issue by jfbrennan** [formatjs/formatjs-old#209]
**Which package?**
IntlMessageFormat

**Describe the bug**
I do `new IntlMessageFormat('My name is {name}.', 'en-US')` and that results in "TypeError: IntlMessageFormat is not a constructor".

**To Reproduce**

- I'm using Node.js v10.15.3 and Express 4.16.3
- I've installed https://www.npmjs.com/package/full-icu because Format.js says I need full ICU (I'm not willing to build a new Node binary, so I'm using this which seems ok...)
- I then start Node with `node --icu-data-dir=node_modules/full-icu server.js`
- My app has `const IntlMessageFormat = require('intl-messageformat')`
- And then in a route the app does:
```
const msg = new IntlMessageFormat('My name is {name}.', 'en-US');
console.log(msg.format({name: 'Bob'}));
```
- And that fails resulting in the error message above
- I have confirmed that `Intl` works as expected using a non en-US locale. Above my `new IntlMessageFormat(...)` code I have this and it works great:
```
console.log(new Intl.DateTimeFormat('es', {month: 'long'}).format(date)); // => "enero"
```

 

**Expected behavior**
```
const msg = new IntlMessageFormat('My name is {name}.', 'en-US');
console.log(msg.format({name: 'Bob'})); // => "My name is Bob."
```

**Desktop (please complete the following information):**

- OS: macOS Sierra 10.12.6
- Browser N/A
- Version Node.js v10.15.3

**Comment by longlho** [comment]
I think it's a `default` interop issue where you can either do:

`import IntlMessageFormat from 'intl-messageformat'`

OR

`const IntlMessageFormat = require('intl-messageformat').default`

I'll update the doc accordingly

**Comment by jfbrennan** [comment]
`const IntlMessageFormat = require('intl-messageformat').default` did it. Thanks
