### ISSUE TITLE
Use single-quotes for escaping instead of back-slashes?

### ISSUE THREAD

**Issue by ericf** [formatjs/formatjs-old#21]
The ICU Message syntax uses single-quotes for escaping, we probably want to do the same.
http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping

**Comment by ericf** [comment]
Java Docs give this guidance:

> Recommendation: Use the real apostrophe (single quote) character ’ for human-readable text, and use the ASCII apostrophe (' ' ) only in program syntax, like quoting in MessageFormat. See the annotations for U+0027 Apostrophe in The Unicode Standard.

http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html

**Comment by longlho** [comment]
fixed in #134
