### ISSUE TITLE
Values placed in ' ' are not replaced

### ISSUE THREAD

**Issue by luciaam** [formatjs/formatjs-old#210]
**Which package?**
intl-messageformat

**Describe the bug**
Messages with values placed in ' ' misinterpreted.

**To Reproduce**

1. Define a message with a placeholder within '' i.e.:
`var msg = new IntlMessageFormat('My name is \'{name}\'.', 'en-US');`
2. Try to format it with a name
`var output = msg.format({name: "Eric"});`
3. See the output: 
`console.log(output);` _// => "My name is {name}."_

**Expected behavior**
The expected output would be _"My name is 'Eric'."_

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: N/A
- Version Node.js v10.15.3

**Comment by longlho** [comment]
ICU message format uses apostrophe to escape so you need to double
apostrophe (`''`) to get the character to show up.

**Comment by longlho** [comment]
Example: https://codesandbox.io/s/react-intl-test-jznj1

**Comment by luciaam** [comment]
Thanks for the hint
