### ISSUE TITLE
License for @formatjs/intl-pluralrule is mismatching with License in package.json

### ISSUE THREAD

**Issue by dyrby76** [formatjs/formatjs-old#212]
**Which package?**
intl-pluralrules (observed in version 1.3.0)

**Describe the bug**
package.json says: License = MIT
License.md file says: License = BSD-3

**To Reproduce**

1. Open the two files and look for the license information

**Expected behavior**
Expected the licenses to match.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by longlho** [comment]
Since this is a monorepo there're some mixed licensing going on. The fix is probably to move License files to each subrepo accordingly

cc @redonkulus
