### ISSUE TITLE
Using an @ symbol before a variable causes internal ids to leak

### ISSUE THREAD

**Issue by solomon23** [formatjs/formatjs-old#217]
**Which package?**
intl-messageFormat

**Describe the bug**
You can't do this
`intl.formatMessage({ id: 'my.id', defaultMessage: 'hi @{there}' }, { there: '2008' })`

it'll output this
`hi 1570551119869_1`

**Expected behavior**
This should translate and put in the 2008 instead of internal id

This is happening in here:
https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/src/formatters.ts
line 247

The token and regex is incorrect.  It could be fixed by making the regex less greedy.  Something like `@@([0-9].*?)@@` but really the problem is using string characters that aren't escaped inside a string.  You'll always run into problems using tokens this way unless you escape the originals. 

My pseudo language code buffers english words with @ symbols and that is causing problems as well.

**Comment by longlho** [comment]
Thanks for reporting we'll take a look at it asap

**Comment by solomon23** [comment]
We're kind of in a pickle with this issue.  There's no version of v3 that doesn't contain this bug and we can't output our copyright string on our website without it having this long string of numbers in it.  Since you use a mono repo I'm having a hard time forking just `intl-messageformat` so I can add my own patch until a real fix is in.

**Comment by longlho** [comment]
1 potential work around is to use the Unicode string instead of @ until I
can fix it. I'm currently on vacation so won't be able to fix until end of
next week

**Comment by h-arlt** [comment]
Unicode equivalent of '@' won't work as it has the same value in memory as '@'. However, putting a Unicode zero-width space `\u200b` between '@' and '{' did work for me.

**Comment by longlho** [comment]
hmm I added a test but cannot reproduce this issue 9422f670d459b4f7572c3b7d36f99e792bcb0a74

**Comment by solomon23** [comment]
I can't get your unit tests to run. I've done an npm install and npm run test and get various failures.  However, looking through your code it looks like the error happens in formatHTMLMessage.  That's where it's adding the @@ tokens
