### ISSUE TITLE
currently `{variable, number, currency}` doesn't really work

### ISSUE THREAD

**Issue by drewfish** [formatjs/formatjs-old#22]
I get the following error: `Currency code is required when style is currency`.

We can do better, by getting the currency for the current locale. As java does:
http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html

**Comment by drewfish** [comment]
(pssst.... https://www.npmjs.org/package/currency-codes)

**Comment by ericf** [comment]
Relates to: https://github.com/yahoo/formatjs-site/issues/86
