### ISSUE TITLE
More breaking changes in intl-messageformat-parser v3.0.0 than described

### ISSUE THREAD

**Issue by westrem** [formatjs/formatjs-old#242]
**Which package?**
intl-messageformat-parser

**Describe the bug**
Version v3.0.0, more specifically this commit and line: https://github.com/formatjs/formatjs/commit/5661177#diff-69e510a7ae71b0e68b287c24c675d4e7R184

introduces `keyword` which is more limited to previously used `chars`. This new `keyword` is used in various other places, meaning all those places became limited in terms of characters allowed to use as well.

The **"bug"** is that this is nowhere mentioned in the Changelog https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat-parser/CHANGELOG.md making it very easy to miss for anyone updating to v3+ from previous version. Case in point is the `react-intl` package, where the [Upgrade Guide for react-intl@3.x](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#placeholder-argument-syntax-change) points out the new limitation of `-` character, but does not mention others, like `:` for example.

**To Reproduce**
Before `react-intl@3.x`, this was a valid syntax for select statement:

```
{variable, select,
    option:1 {Option 1}
    option:2 {Option 2}
}
```

After https://github.com/formatjs/formatjs/commit/5661177#diff-69e510a7ae71b0e68b287c24c675d4e7R184 and https://github.com/formatjs/react-intl/commit/f59607e

this syntax causes error saying that unexpected symbol `:` was encountered, and `{` was expected.

**Expected behavior**
Both changelog and update guide mentioned above should mention ALL new limitations caused by the commits mentioned here.

**Comment by longlho** [comment]
PR's welcome :)
