### ISSUE TITLE
[intl-messageformat@7.2.2] Date & number formatting regression in IE11

### ISSUE THREAD

**Issue by antoinerey** [formatjs/formatjs-old#255]
**Which package?**

intl-messageformat

---

**Describe the bug**

The 7.2.2 version introduced a regression on IE. Numbers and Dates are not formatted using the given locale anymore, but using the english one.

---

**To Reproduce**

Using the **latest** version (**7.5.0** as of today)
1. Using Chrome, navigate to https://csb-dzt9z.netlify.com 
2. See the number and date formatted using the **french locale**
3. Using IE11, navigate to https://csb-dzt9z.netlify.com
4. See the number and date formatted using the **english locale**

Testing environment: https://csb-dzt9z.netlify.com 
Codesandbox: https://codesandbox.io/s/issue-123-intl-messageformat750-dzt9z

—

Using the **7.2.2** version
1. Using Chrome, navigate to https://csb-ee8gr.netlify.com
2. See the number and date formatted using the **french locale**
3. Using IE11, navigate to https://csb-ee8gr.netlify.com
4. See the number and date formatted using the **english locale**

Testing environment: https://csb-ee8gr.netlify.com
Codesandbox: https://codesandbox.io/s/issue-123-intl-messageformat722-ee8gr

—

Using the **7.2.1** version (**working fine**)
1. Using Chrome, navigate to https://csb-d7mmn.netlify.com
2. See the number and date formatted using the **french locale**
3. Using IE11, navigate to https://csb-d7mmn.netlify.com
4. See the number and date formatted using the **french locale as well**.

Testing environment: https://csb-d7mmn.netlify.com
Codesandbox: https://codesandbox.io/s/issue-123-intl-messageformat721-d7mmn

---

**Expected behavior**

Both number and date should be formatted using the provided locale, not using the english one.

---

**Screenshots**

Latest version (**7.5.0**) on Chrome
![image](https://user-images.githubusercontent.com/3336873/68291631-8f6d1900-008a-11ea-91d0-c22bca245552.png)

Latest version (**7.5.0**) on IE11
![image](https://user-images.githubusercontent.com/3336873/68291665-a14ebc00-008a-11ea-9199-d91b5721c8a1.png)

—

**7.2.2** version on Chrome
![image](https://user-images.githubusercontent.com/3336873/68291688-ae6bab00-008a-11ea-8ed9-5a56f285698a.png)

**7.2.2** version on IE11
![image](https://user-images.githubusercontent.com/3336873/68291726-c2171180-008a-11ea-9444-1bc6e505687e.png)

—

**7.2.1** version on Chrome
![image](https://user-images.githubusercontent.com/3336873/68291749-ce9b6a00-008a-11ea-848d-769701c4af9b.png)

**7.2.1** version on IE11
![image](https://user-images.githubusercontent.com/3336873/68291779-da872c00-008a-11ea-8c95-b2eaccedf84e.png)

---

**Desktop:**

- OS: Windows (simulated on BrowserStack)
- Browser: IE
- Version: 11

**Comment by longlho** [comment]
Thanks for reporting. Do you have any stack traces? We'll take a look soon.

**Comment by antoinerey** [comment]
There is no error in the console so no stack traces are dumped, if this is what you mean.

**Comment by nbouvrette** [comment]
Are you using the Intl polyfill? I saw similar issues trying to force the polyfill on Chrome but also noted that the latest UMD polyfill is not compatible with IE11 in its current JS syntax version.

**Comment by antoinerey** [comment]
I first tried using https://polyfill.io, but the downloaded script was empty, probably because IE11 already supports both the Intl API and the french locale.

Even by forcing the polyfill using `flags=always` did not fix the issue.

1. https://polyfill.io/v3/polyfill.min.js?features=Intl~.locale.fr-FR
2. https://polyfill.io/v3/polyfill.min.js?flags=always&features=Intl~.locale.fr-FR

---

I also tried to polyfill Intl manually using the `intl` package, but the result was the same.

**Comment by nbouvrette** [comment]
When I load in `intl-messageformat` (7.5.0) IE11 I get the following console error:

```
SCRIPT5022: Intl.PluralRules is not available in this environment.
Try polyfilling it using "@formatjs/intl-pluralrules"
intl-messageformat.js (2700,25)
```

So I tried to also add `@formatjs/intl-pluralrules` (1.3.1) but when I load `/dist/umd/polyfill-with-locales.js`, I get: 

```
SCRIPT1014: Invalid character
polyfill-with-locales.js (349,33)
```

It seems related to a transpiling problem but, it might help solve your issue by fixing this issue.

I also confirm the polyfill links you provided are empty.

**Comment by longlho** [comment]
So the issue is that we try to resolve locale for all functionality before committing to a specific locale, and in the IE11 case because there's no `Intl.PluralRules` data for `fr-FR`, it falls back to `en`.
In this specific use case since message doesn't care about PluralRules this becomes confusing so I'll put up a fix soon.

**Comment by antoinerey** [comment]
I confirm that your PR did fix this issue. 👌 

Testing environment: https://csb-vjiv9.netlify.com
Codesandbox https://codesandbox.io/s/issue-123-intl-messageformat752-vjiv9

Thanks @longlho!
