### ISSUE TITLE
support for converting the parsed object back to ICU message

### ISSUE THREAD

**Issue by Alino** [formatjs/formatjs-old#273]
does this library also convert back to ICU message?
If not, does anyone has a suggestion for me?

I need to parse ICU messages, change it's content, and then convert back to ICU message.

**Comment by longlho** [comment]
it is supported using https://unpkg.com/intl-messageformat-parser@3.2.2/dist/printer.js

```
import {printAST} from 'intl-messageformat-parser/dist/printer'

printAST(ast) // gives you string
```

Note that this only work in Node 12+ and modern browsers because of the regex we're using.
