### ISSUE TITLE
Incorrect license link on README for multiple packages

### ISSUE THREAD

**Issue by camyyssa** [formatjs/formatjs-old#282]
**Which package?**
README for the entire repo

**Describe the bug**
The README has a license section, but the file you're linking to doesn't exist. This seems to be the case in multiple places in the repo. 

Ignore the `/package/` entries, but a search all for `license` in the project shows that it's used in a couple of the project's own subpackages https://github.com/formatjs/formatjs/search?p=5&q=license&unscoped_q=license 

**To Reproduce**

1. Go to 'https://github.com/formatjs/formatjs#license'
2. Click on the 'LICENSE file' link with url https://github.com/formatjs/formatjs/blob/master/LICENSE.md
3. See 404 page from Github. 

**Expected behavior**
Read the license document. Couldn't find anything on a license in package.json, or in the rest of the repo. It looks like the file got deleted at some point, but the readme was not updated

**Comment by longlho** [comment]
Thanks for reporting. Some subpackages has a different license so it's a little tricky. I'll take a look asap

**Comment by longlho** [comment]
fixed in 340121eed77f761e922358c0d64ba584f58ed2d8
