### ISSUE TITLE
Support node 13.1.0

### ISSUE THREAD

**Issue by FilipStenbeck** [formatjs/formatjs-old#283]
**Which package?**
@formatjs/macro

**Is your feature request related to a problem? Please describe.**
We want to run node.js 13.1.0. When running yarn in our application we get
```
@formatjs/macro@0.2.1: The engine "node" is incompatible with this module. Expected version "8.x || 10.x || 12.x". Got "13.1.0"
```

**Describe the solution you'd like**
We want support for running 13.1.0

**Comment by longlho** [comment]
latest version doesn't have this restriction anymore so it should work :)

**Comment by FilipStenbeck** [comment]
My bad, thanks.

**Comment by codingKulot** [comment]
yarn install --ignore-engines
