### ISSUE TITLE
HTML tags inside FormattedMessage throws error on the server

### ISSUE THREAD

**Issue by eliseumds** [formatjs/formatjs-old#285]
I have a message:

```js
<FormattedMessage
  id="my_beautiful_msg"
  defaultMessage="Include this code snippet in the <head></head> section of your page's HTML"
/>
```

When it's rendered on the server, an error is logged:

```
[React Intl] Error formatting the default message for: "my_beautiful_msg"
Error: Cannot format XML message without DOMParser
    at new FormatError (.../node_modules/intl-messageformat/dist/formatters.js:29:28)
    at Object.formatHTMLMessage (.../node_modules/intl-messageformat/dist/formatters.js:273:15)
    at IntlMessageFormat.formatHTMLMessage (.../node_modules/intl-messageformat/dist/core.js:70:33)
    at formatMessage (.../node_modules/react-intl/dist/format.js:209:47)
    at Object.children (.../node_modules/react-intl/dist/components/message.js:73:25)
    at ReactDOMServerRenderer.render (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3664:55)
    at ReactDOMServerRenderer.read (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at Object.renderToString (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at Object.then (.../src/clients/bm/dist/server.js:47124:88)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[React Intl] Cannot format message: "my_beautiful_msg", using message source as fallback.
```

CodeSandBox (with server-side rendering): https://codesandbox.io/s/example-server-side-rendering-dxfw2

**Comment by longlho** [comment]
yeah you'd need to polyfill that in Node env: https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats

**Comment by eliseumds** [comment]
@longlho I didn't use *FormattedHTMLMessage*, but *FormattedMessage*, so the caveats shouldn't apply in my case. I don't want to embed HTML but rather render it as raw string (escaped), which happens, but this additional step to embed HTML should not be there.

**Comment by longlho** [comment]
ah gotcha sry I misunderstood. I'll take a look soon.

**Comment by longlho** [comment]
ok so this is expected, if you want to silence the error we do expose `onError` where u can selectively ignore them (we default to `console.log`)

**Comment by eliseumds** [comment]
So the only way to avoid a dirty hack like overriding *onError* is to pass a custom value with the tag name?

```js
<FormattedMessage
  id="my_beautiful_msg"
  defaultMessage="Include this code snippet in the {tag} section of your page's HTML"
  values={{
    tag: '<head></head>'
  }}
/>
```

Or is there some special syntax involving something like backtick/backslash?

**Comment by longlho** [comment]
Yup custom value works too. It comes down to us not being able to detect if `<head></head>` is actually rich text formatting, or an error so we fail-fast.

**Comment by kruulik** [comment]
I'm having a somewhat related issue: https://github.com/formatjs/formatjs/issues/367

**Comment by lxcid** [comment]
I face similar issue:

Can't server side render

```jsx
<FormattedMessage
  id="general.download_on_the_app_store"
  defaultMessage="<span_top>Download on the</span_top><span_bottom>App Store</span_bottom>"
  values={{
    span_top: msg => <span className="top-line">{msg}</span>,
    span_bottom: msg => <span className="bottom-line">{msg}</span>,
  }}
/>
```

**Comment by longlho** [comment]
@lxcid https://github.com/formatjs/formatjs/issues/285#issuecomment-556844692

**Comment by raulfdm** [comment]
Just for further references, in my project I have a custom node server running everything. I fix that by doing:

1. Add `xmldom`

```bash
yarn add xmldom @types/xmldom
```

2. In my server.ts, I imported it and attach to global:

```ts
// server.ts
// ... other imports
import { DOMParser } from 'xmldom';

global.DOMParser = DOMParser;
```
3. As I'm using TypeScript, I had to add this new global to my global types:

```ts
// next-env.d.ts

declare module NodeJS {
  interface Global {
    DOMParser: DOMParserStatic;
  }
}
```

No errors anymore. :)

**Comment by shirleymiao** [comment]
We did something similar to resolve this, also by exposing a DOMParser.  

```
import { JSDOM } from "jsdom"

const document = new JSDOM()
global["DOMParser"] = document.window.DOMParser
```

**Comment by longlho** [comment]
Our newest version will get rid of this dependency but does come with some restrictions

**Comment by raulfdm** [comment]
> Our newest version will get rid of this dependency but does come with some restrictions

with latest version (4.3^), no need to add `jsdom` or `xmldom`. I just upgrade to this version and remove those dependencies
