### ISSUE TITLE
IntlMessageFormat.__addLocaleData is no longer a function in version 3.1.1

### ISSUE THREAD

**Issue by maximilianschmitt** [formatjs/formatjs-old#29]
### Which package?

intl-messageformat@3.1.1

### Expected behavior

```
IntlMessageFormat.__addLocaleData({"locale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-AT","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-BE","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-CH","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-LI","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-LU","parentLocale":"de"});
```

Should register the locale data. This is how the data comes from e.g. https://cdnjs.cloudflare.com/ajax/libs/intl-messageformat/3.0.0/locale-data/de.js

### Current behavior

Throws a TypeError because `IntlMessageFormat.__addLocaleData` is undefined and not a function.

### Step to reproduce

1. Install `intl-messageformat@3.1.1`
2. Run the following code in a node script:

```
const IntlMessageFormat = require("intl-messageformat").default;

IntlMessageFormat.__addLocaleData({"locale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-AT","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-BE","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-CH","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-LI","parentLocale":"de"});
IntlMessageFormat.__addLocaleData({"locale":"de-LU","parentLocale":"de"});
```

Here is a live example on repl-it: https://repl.it/@maximilianschmi/intl-messageformat-error

**Comment by longlho** [comment]
Yeah we no longer need `__addLocaleData` anymore since we rely on `supportedLocalesOf` natively to resolve parent locale. You should not need `locale-data` anymore

**Comment by longlho** [comment]
Feel free to reopen if u see further issue but this is working as designed

**Comment by maximilianschmitt** [comment]
Hm there still seems to be issues. It works without this locale data on Chrome but on Safari I get errors like the following when using intl-messageformat@3 without loading locale-data from some CDN:

<img width="834" alt="Screenshot 2019-05-27 at 11 17 00" src="https://user-images.githubusercontent.com/3694962/58409767-0da3a900-8071-11e9-8208-fb0655f9d693.png">

Any idea what I might be missing?

**Comment by maximilianschmitt** [comment]
(I unfortunately can't reopen the issue)

**Comment by longlho** [comment]
For version 3 we rely on intl-pluralrules polyfill so it should work if you
add that before importing intl-messageformat. I think the release changelog
& README should have it.

**Comment by maximilianschmitt** [comment]
Thanks for getting back to me @longlho. Seems to work nicely with `intl-pluralrules` :)
