### ISSUE TITLE
ESlint error shown incorrectly when using an object with intl.formatMessage()

### ISSUE THREAD

**Issue by priyajeet** [formatjs/formatjs-old#304]
Followup to #292 

**Which package?**
eslint-plugin-formatjs v1.5.0

**Describe the bug**
The following should ideally be equivalent. In both cases there should be no error shown. 1st image shows correctly, the 2nd image where object is inlined, is incorrect. In the examples below `description` is coming from say a function arg/prop.

<img width="463" alt="Screen Shot 2019-11-25 at 1 19 17 PM" src="https://user-images.githubusercontent.com/1075325/69578984-70292380-0f86-11ea-84c4-b728206221c9.png">

<img width="959" alt="Screen Shot 2019-11-25 at 1 19 45 PM" src="https://user-images.githubusercontent.com/1075325/69578985-70292380-0f86-11ea-9456-8e522e7eff4f.png">

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
