### ISSUE TITLE
intl-messageformat readme attempts to redefine const

### ISSUE THREAD

**Issue by moodyjmz** [formatjs/formatjs-old#305]
**Which package?**
intl-messageformat

**Describe the bug**

README.md line 57

```js
const output;
```

should be

```js
let output;
```
**To Reproduce**
Attempt to use sample code.

1. setup to use use intl-messageformat
2. Copy sample code
3. run

**Expected behavior**
It works

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
