### ISSUE TITLE
intl-locales-supported false positive

### ISSUE THREAD

**Issue by andrew--r** [formatjs/formatjs-old#306]
**Which package?**
`intl-locales-supported`

**Describe the bug**
`intl-locales-supported` returns `true` when some of default `intlConstructors` are missing.

**To Reproduce**

1. Open [codesandbox](https://codesandbox.io/s/priceless-cori-fn9hr?fontsize=14&hidenavigation=1&theme=dark) in Safari
4. See result and `Intl.PluralRules` mismatch

**Expected behavior**
`intl-locales-supported` should return `false` if any of default `intlConstructors` are missing.

**Screenshots**

<img width="1171" alt="Screen Shot 2019-11-26 at 14 52 26" src="https://user-images.githubusercontent.com/2734841/69627797-68d44980-105c-11ea-93d5-187f6f5e9ae3.png">

**Desktop:**

- OS: macOS High Sierra 10.13.6
- Browser: Safari
- Version: 12.1

**Additional context**

I believe problem is in the condition https://github.com/formatjs/formatjs/blob/master/packages/intl-locales-supported/src/index.ts#L37-L38. I’d suggest setting default value to `constructorsToCheck`:

```
export default function areIntlLocalesSupported(
  locales: string | string[],
  constructorsToCheck: Array<IntlConstructor> = [
    Intl.DateTimeFormat,
    Intl.NumberFormat,
    Intl.PluralRules,
  ]
): boolean {}
```

I can make a PR with a fix.

**Comment by longlho** [comment]
So the reason it was done that way is for backwards compatibility (e.g people who didn't need `Intl.PluralRules` suddenly got a different result). Unfortunately that means you'd have to pass in the array at the callsite. I've updated the README accordingly.
