### ISSUE TITLE
selectUnit inconsistent logic

### ISSUE THREAD

**Issue by Klemensas** [formatjs/formatjs-old#310]
**Which package?**
`@formatjs/intl-utils`

**Describe the bug**
`selectUnit` uses different logic for month and year determination than other units resulting in confusing dates. Is this really the intended behavior?

**To Reproduce**
```ts
selectUnit(new Date('2019-10-31'), new Date('2019-11-05')) // { unit: 'month', value: 1 }
selectUnit(new Date('2019-01-05'), new Date('2018-12-30')) // { unit: 'year', value: 1 }
```
**Expected behavior**
```ts
selectUnit(new Date('2019-10-31'), new Date('2019-11-05')) // { unit: 'week', value: 1 }
selectUnit(new Date('2019-01-05'), new Date('2018-12-30')) // { unit: 'week', value: 1 }
```

**Comment by longlho** [comment]
So we received this issue every now and then that I've included a section in the README to explain this.

**Comment by Klemensas** [comment]
Okay, my bad, thanks.

**Comment by longlho** [comment]
Thanks for reporting! :)
