### ISSUE TITLE
No matching version found for @formatjs/intl-utils@^1.6.0

### ISSUE THREAD

**Issue by bo-ora** [formatjs/formatjs-old#340]
**Which package?**
@formatjs/intl-listformat

**Describe the bug**
I'm getting an error from NPM while installing **react-intl**:
`No matching version found for @formatjs/intl-utils@^1.6.0`
`It was specified as a dependency of '@formatjs/intl-listformat'`

I've checked NPM registry info and got correct info about published 1.6.0 version:
`npm view @formatjs/intl-utils`
`...`
`dist-tags:
latest: 1.6.0`

**To Reproduce**
1. Add `react-intl` to the package.json dependencies.
2. Run `npm i`

**Expected behavior**
`react-intl` installed without errors.

**Desktop:**
- OS: Linux Mint 18.2.0 'Sonya'

**Comment by longlho** [comment]
This seems like a transient issue. Can you retry?

**Comment by bo-ora** [comment]
@longlho indeed, thanks.
