### ISSUE TITLE
Prod building with intl-messageformat in NG CLI fails

### ISSUE THREAD

**Issue by moodyjmz** [formatjs/formatjs-old#349]
**Which package?**
intl-messageformat
intl-utils

**Describe the bug**

When using formats in an NG project prod build does not work.

Running `ng build` works
Running `ng build --prod` does not

I've created an issue with NG CLI here, with a stackblitz demo

https://github.com/angular/angular-cli/issues/16289

I have found directly referencing files in list does work, but I'm loath to do that really as will create issues where es6 is used cleanly.

In Vue and React there are no issues - so my thought is that this problem lies with ng cli, however thought I'd mention here as well.

**To Reproduce**

1. Create ng project
2. add `import IntlMessageFormat from "intl-messageformat";` to components.ts
3. run `ng build --prod`
3. Open in IE (or mod build to force Chrome to run es5)

**Expected behavior**
Runs as normal

- OS: Mac/Windows
- Browser any
- Version *

**Comment by longlho** [comment]
Unfortunately I can't really offer a lot of help here due to myself not using `ng cli`.

**Comment by moodyjmz** [comment]
no worries, given that it works elsewhere, I think the issue lies in ng cli, just thought I'd mention it.

**Comment by moodyjmz** [comment]
This appears related to a bug in webpack.

NG is now using [webpack 4.41.4](https://github.com/webpack/webpack/releases/tag/v4.41.4) since [NG CLI  8.3.21](https://github.com/angular/angular-cli/releases/tag/v8.3.21) and addresses some edge cases regarding modules.

Closing as is not an issue anymore.
