### ISSUE TITLE
intl-messageformat breaks due to missing dependency

### ISSUE THREAD

**Issue by lg-kialo** [formatjs/formatjs-old#350]
**Which package?**
`intl-messageformat`

**Describe the bug**
Build breaks because of missing dependency.
This line https://github.com/formatjs/formatjs/blob/eaa0039c90533b09b0c03aa9dc9cd8c605405dba/packages/intl-messageformat-parser/src/skeleton.ts#L2 introduced a dependency on `@formatjs/intl-unified-numberformat` which is only declared in `devDependencies` and not in `dependencies` of the `package.json` of `intl-messageformat`.

**To Reproduce**

1. Add `intl-messageformat` version 7.7.1 as dependency.
2. Compile your project using the typescript compiler.
3. Get the error message `Cannot find module '@formatjs/intl-unified-numberformat'.`

**Expected behavior**
The compilation is successful.

**Comment by longlho** [comment]
mind putting a quick PR in? this should be easy to fix :)
