### ISSUE TITLE
[eslint-plugin-formatjs] `defineMessages` with placeholders create eslint errors

### ISSUE THREAD

**Issue by e110c0** [formatjs/formatjs-old#356]
**Which package?**
eslint-plugin-formatjs

**Describe the bug**
I'm trying to figure the new eslint plugin rules out and running into the following issue: when using `defineMessages` to setup messages and the rule `formatjs/enforce-placeholders` is active, there is no way around the linter errors but deactivating the rule.

**To Reproduce**

1. activate `formatjs/enforce-placeholders`
2. lint the following code

```
const messages = defineMessages({
  example: {
    id: 'example',
    defaultMessage: 'some test with a placeholder: { foo }',
  },
});
```

**Expected behavior**

Instead of reporting an issue in defineMessages with placeholders, it should be enforced only when the message is created (FormattedMessage, intl.formatMessage and such)

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
