### ISSUE TITLE
__addUnitLocaleData should be renamed __addLocaleData in the docs ?

### ISSUE THREAD

**Issue by fabien88** [formatjs/formatjs-old#358]
**Which package?**
intl-unified-numberformat

**Describe the bug**
The docs (README.md) stipulate this :
```js
if (typeof Intl.NumberFormat.__addUnitLocaleData === 'function') {
  Intl.NumberFormat.__addUnitLocaleData(
    require('@formatjs/intl-unified-numberformat/dist/locale-data/zh.json') // locale-data for zh
  );
  Intl.NumberFormat.__addUnitLocaleData(
    require('@formatjs/intl-unified-numberformat/dist/locale-data/en.json') // locale-data for en
  );
}
```

but ```__addUnitLocaleData``` seems to no longer exists as mentionned in the changelog (2.0.0) :
 **@formatjs/intl-unified-numberformat:** rename __addUnitLocaleData to __addLocaleData ([d251733](https://github.com/formatjs/formatjs/commit/d251733))

**Comment by longlho** [comment]
Thanks for reporting. PR's definitely welcome!
