### ISSUE TITLE
[v3.x intl-message-parser] Template tokens are not recognized if encapsulated in single quotes

### ISSUE THREAD

**Issue by raix** [formatjs/formatjs-old#359]
**Which package?**
intl-messageformat-parser

**Describe the bug**
Template tokens are not recognized if encapsulated in single quotes.

**To Reproduce**

1. parse("Hello '{foo}'")
2. verify that only a type literal node was created

**Expected behavior**

Expected to have a literal node on each side of a string variable node

**Screenshots**

Actual:
```
Array [
  Object {
    "type": 0,
    "value": "Test single quote {identifier}",
  },
]
```

Expected:
```
Array [
  Object {
    "type": 0,
    "value": "Test single quote '",
  },
  Object {
    "type": 1,
    "value": "identifier",
  },
  Object {
    "type": 0,
    "value": "'",
  },
]
```

**Desktop (please complete the following information):**

- OS: mac
- Browser node
- Version 10.x

**Additional context**
For now we just do `parse(message.replace(/{/g, " {").replace(/}/g, "} "))` to generate the ast.

(thank you for starting up development again on this project :) )

**Comment by longlho** [comment]
ICU message format uses `'` to escape instead of `\` so you gotta double escape it, e.g: `Test single quote ''{identifier}''`

**Comment by raix** [comment]
bugger so the parser is now compliant with the spec...
Thanks :)
