### ISSUE TITLE
Unable to format both html tag and custom value

### ISSUE THREAD

**Issue by kruulik** [formatjs/formatjs-old#367]
**Which package?**
`FormattedMessage` 

**Describe the bug**

I'm following this example: 
`<FormattedMessage
  id="app.greeting"
  description="Greeting to welcome the user to the app"
  defaultMessage="Hello, <b>Eric</b> {icon}"
  values={{
    b: (...chunks) => <b>{chunks}</b>,
    icon: <svg />,
  }}
/>`

Where the message I am passing  in through `id` is something like "Hello, my \<b>name\</b> is Bob {icon}" and my value props look like this: 
`
values={{
  b: (...chunks) => <MyTextComponent>{chunks}</MyTextComponent>,
}}`

When I use `FormattedMessage`, the `<b></b>` tags are printed to the screen. When I use FormattedHTMLMessage, `{icon} ` returns `[object Object]`. I can't get both to work at once, but both work individually.

**Comment by longlho** [comment]
Can you provide a codesandbox.io demo link?
