### ISSUE TITLE
intl.FormatMessage() message extraction breaks existing usage of this function

### ISSUE THREAD

**Issue by macca16** [formatjs/formatjs-old#37]
Pull https://github.com/formatjs/babel-plugin-react-intl/pull/165 was committed in https://github.com/formatjs/formatjs/commit/b57953e8dda7638632f4e40f968acf84954ba5ba and breaks usages of injected `intl.formatMessage()` that do not follow the structure:

```
            this.props.intl.formatMessage({
                id: 'foo.bar.biff',
                defaultMessage: 'Hello Nurse!',
                description: 'Another message',
            })

```
###  BUG REPORT
Pull https://github.com/formatjs/babel-plugin-react-intl/pull/165 was committed in https://github.com/formatjs/formatjs/commit/b57953e8dda7638632f4e40f968acf84954ba5ba 

It added support for extracting messages from injected `intl.FormatMessage()` calls. Unfortunately with it being enabled by default it is causing extraction failures where used like shown here:

```
const translations = defineMessages({
    mystring: {
        id: 'keyname',
        description: 'my desc',
        defaultMessage: 'my english',
    },
});
```
example usage:
`this.props.intl.formatMessage(translations.mystring)`

Without the option to make this change opt in and no obvious way to opt out of this functionality I needed for now to downgrade babel-plugin-react-intl to 3.0.1

### Expected behavior
I'd expect backward compatibility via the option to turn on extraction of messages defined via `intl.FormatMessage()` explicitly rather than implicitly.

### Current behavior
Throws an error 

`throw path.buildCodeFrameError(`[React Intl] \`${callee.node.name}()\` must be ` + 'called with an object expression with values ' + 'that are React Intl Message Descriptors, also ' + 'defined as object expressions.');`

### Step to reproduce for BUG REPORT
- In a project that uses injectIntl and connect to inject intl into components
```
import { connect } from 'react-redux';
import { injectIntl } from 'react-intl';
```
- Add a usage of intl as follows:
```
const translations = defineMessages({
    mystring: {
        id: 'keyname',
        description: 'my desc',
        defaultMessage: 'my english',
    },
});
```
example usage:
`this.props.intl.formatMessage(translations.mystring)`
- Observe that on message extraction the following error is received:
`throw path.buildCodeFrameError(`[React Intl] \`${callee.node.name}()\` must be ` + 'called with an object expression with values ' + 'that are React Intl Message Descriptors, also ' + 'defined as object expressions.');`

**Comment by swernerx** [comment]
Please note that I tweaked the processing a bit in this PR to allow mixed usage: https://github.com/formatjs/formatjs/pull/43 - This might be interesting for projects which may want to migrate away from `defineMessages` and use `intl.formatMessage` directly.
