### ISSUE TITLE
[@formatjs/intl-relativeformat] Weird (wrong?) behavior

### ISSUE THREAD

**Issue by Nasicus** [formatjs/formatjs-old#379]
I came here from `react-intl`.

I basically only need the `selectUnit` value and I don't understand why it's implemented the way it is.

The main problem is, if you pass in a date which is in the next year - even if today is the `12/31/2019` and you pass in `01/01/2020` - it will give you back `{ unit: 'year', value: 1}`.

I copied the code an slightly modified it (not fully tested obviously) and it seems to work much better. Since I invested almost no time in it, I'm just trying to understand why it's not implemented differently (the effort seems low, is what I mean to say).

Is it really just a bug or do I oversee something critical?

My version:

The things I changed are basically, that they "year" is the last "resort", I added thresholds for weeks and months and check them accordingly.
 
Is this a too naive approach? Am I missing something?

https://github.com/Nasicus/formatjs/compare/5b2eea3fb6f2f71535b6f93ca095f51ddf241ecc..39e6cc9c6b7fcaa1aae52e522e50ea9061ce48bb

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/issues/1397#issuecomment-521055393 should provide more context on why it is this way. TL;DR: `selectUnit` is only useful as a transitioning function but you should create your own that fits your use case.
