### ISSUE TITLE
[intl-unified-numberformat] [firefox] Regular expression error when using polyfill

### ISSUE THREAD

**Issue by stefankram** [formatjs/formatjs-old#419]
**Which package?**
`intl-unified-numberformat`

**Describe the bug**
Executing the following code in Firefox:
```
import '@formatjs/intl-unified-numberformat/polyfill';
import '@formatjs/intl-unified-numberformat/dist/locale-data/en-US.js';
console.log(new Intl.NumberFormat('en-US', { notation: 'compact' }).format(987654321));
```
Results in the following error: 
```
SyntaxError: invalid identity escape in regular expression
```
Note that this code works perfectly fine in Chrome and Safari.

**To Reproduce**
Run the above code in Firefox to see the error in the console.

**Expected behavior**
Both Chrome and Safari will log `988M` which I would expect to be logged in Firefox.

**Screenshots**
Error in the Firefox console:
![Screen Shot 2020-01-02 at 3 28 39 PM](https://user-images.githubusercontent.com/13611581/71691159-9c4d7680-2d74-11ea-811e-47e4c5f49a5a.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser Firefox
- Version 71.0 (64-bit)

**Comment by stefankram** [comment]
Seems that this doesn't work in IE 11 either. The console error may give some more insight into what regex is throwing the error:
![Screen Shot 2020-01-02 at 3 37 17 PM](https://user-images.githubusercontent.com/13611581/71691651-f1d65300-2d75-11ea-8a0c-86baf20a06bc.png)
![Screen Shot 2020-01-02 at 3 37 25 PM](https://user-images.githubusercontent.com/13611581/71691660-f4d14380-2d75-11ea-8f2a-d29ad3e72e18.png)

The `S_UNICODE_REGEX` seems to be the cause.

**Comment by longlho** [comment]
Can you try `master`? We've fixed this issue but have not released it.

**Comment by stefankram** [comment]
Just tried it and it works on the latest master, thanks!

**Comment by longlho** [comment]
we released the newest version so closing this.
