### ISSUE TITLE
[intl-messageformat] build break due to breaking changes in transitive dependency

### ISSUE THREAD

**Issue by CarstenLeue** [formatjs/formatjs-old#436]
**Which package?**
intl-messageformat

**Describe the bug**
The versioning of `intl-messageformat` follows the rules of semantic versioning, so I would not expect breaking changes for minor version or patch updates.

However a breaking change has been introduced transitively by a breaking change in a minor version update of `@formatjs/intl-utils` (see https://github.com/formatjs/formatjs/issues/410). This package now requires TS 3.7 to compile and this now also true for `intl-messageformat`. 

The bug is that my project won't compile because of the update in `@formatjs/intl-utils`, although this project only uses 
`"intl-messageformat": "^7.5.2",`

as a dependency. I have no way to pin the version `@formatjs/intl-utils` directly, since my project does not use that component directly.

Also I cannot upgrade to TS 3.7 because other components in my project do not support it.

**Expected behavior**
I expect the public API to remain compatible across minor version or patch updates. Raising the required TS level is an incompatible change.

**Comment by longlho** [comment]
Type definition in reality doesn’t follow semver at all (e.g if you upgrade
@types/react to a patch version there’s no guarantee it compiles). I’ll try
to release a version that pins to older TS.

**Comment by longlho** [comment]
can you try latest version?

**Comment by cahite** [comment]
I tried the latest version and didn't see any errors. Thanks!
