### ISSUE TITLE
[intl-messageformat-parser]: Possible breaking change in using pound symbol?

### ISSUE THREAD

**Issue by cheryly279** [formatjs/formatjs-old#437]
**Which package?**
intl-messageformat-parser

**Describe the bug**
Receiving errors like: The intl string context variable "undefined" was not provided to the string "undefined" recently, could that be related to this update?
https://github.com/formatjs/formatjs/releases/tag/intl-messageformat-parser%403.6.0

I fixed by updating my messages like:

```
    title: {
        id: 'blah.blah.blah',
        defaultMessage: `{score, plural, one {# shopper} other {# shoppers}}`,
    },
```

to 

```
    title: {
        id: 'blah.blah.blah',
        defaultMessage: `{score, plural, one {'#' shopper} other {'#' shoppers}}`,
    },
```

Was this meant to be a breaking change?

**Comment by longlho** [comment]
hmm it's not supposed to break. We'll take a look asap

**Comment by longlho** [comment]
oh seems like a mismatch version cause this issue. If you upgrade intl-messageformat as well that should fix it.

**Comment by pyrocat101** [comment]
@longlho Shall we nuke 3.6.2 and release a new major version of intl-messageformat-parser instead?

**Comment by cheryly279** [comment]
> oh seems like a mismatch version cause this issue. If you upgrade intl-messageformat as well that should fix it.

That worked, thank you!
