### ISSUE TITLE
Bug related to selectUnit

### ISSUE THREAD

**Issue by mormubis** [formatjs/formatjs-old#465]
**Which package?**
`intl-utils`

**Describe the bug**
`selectUnit` results in `{"value": -1, "unit": "year"}` after new years.

**To Reproduce**
``` 
selectUnit(new Date(2019, 10, 30), new Date(2020, 0, 16))
// {"value": 1, "unit": "year"}
```

**Expected behavior**
``` 
selectUnit(new Date(2019, 10, 30), new Date(2020, 0, 16))
// {"value": 1, "unit": "month"}
```

**Comment by longlho** [comment]
Thanks for the PR but we don't accept PRs to `selectUnit` since its output is entirely editorial and will break people. See https://github.com/formatjs/formatjs/tree/master/packages/intl-utils#caveats
