### ISSUE TITLE
intl-messageformat-parser install size is disproportionally large

### ISSUE THREAD

**Issue by Janpot** [formatjs/formatjs-old#475]
**Which package?**

`intl-messageformat-parser`

**Describe the bug**

The [Install size](https://packagephobia.now.sh/result?p=intl-messageformat-parser) of `intl-messageformat-parser` is 188MB. [The bulk of that](https://packagephobia.now.sh/result?p=%40formatjs%2Fintl-unified-numberformat) seems to be taken up by its single dependency `@formatjs/intl-unified-numberformat`, clocking in at 187MB. As far as I can see, this dependency is only used to reference one single [typescript interface](https://github.com/formatjs/formatjs/blob/e825ff5cfe23a24012432ad6f13718badedf6b23/packages/intl-messageformat-parser/src/skeleton.ts#L2): `UnifiedNumberFormatOptions`.
I'm only depending on `intl-messageformat-parser`, but it's pulling in 200 times its own size (and also multiples of the size of my module) in dependencies it is barely using. Is there a way to remove this dependency? Maybe by duplicating that one interface? Or by sharing it between the two packages in a different way?

**To Reproduce**

1. Install `intl-messageformat-parser`
2. inspect `node_modules`

**Expected behavior**

The size of `intl-messageformat-parser` on disk to be magnitudes smaller since it isn't using most of the code that is pulled in.

**Comment by Janpot** [comment]
@pyrocat101 Quick update after doing some digging. It looks like `intl-numberformat` is big because of its dependency on `unicode-12.1.0`. It seems to import only a 2kb regex from this module. The README of `unicode-12.1.0` [states](https://www.npmjs.com/package/unicode-12.1.0#installation) that

> **Note:*** _unicode-12.1.0_ is supposed to be used in build scripts (i.e. as a devDependency), and not at runtime (i.e. as a regular dependency).

It looks like you're using `rollup` to [build](https://github.com/formatjs/formatjs/blob/d11070aaf39c70bd7481f6f146b4fb69b529cb06/packages/intl-unified-numberformat/rollup.config.js#L11) this module. Would it be an idea to make it a `devDependency` and have the regex [injected](https://www.npmjs.com/package/@rollup/plugin-inject) by rollup instead? What do you think?

**Comment by pyrocat101** [comment]
Thanks for the investigation. I will take a look tomorrow :)

**Comment by pyrocat101** [comment]
> It looks like you're using `rollup` to [build](https://github.com/formatjs/formatjs/blob/d11070aaf39c70bd7481f6f146b4fb69b529cb06/packages/intl-unified-numberformat/rollup.config.js#L11) this module. Would it be an idea to make it a `devDependency` and have the regex [injected](https://www.npmjs.com/package/@rollup/plugin-inject) by rollup instead? What do you think?

`rollup` is used to build the UMD distribution of the self-contained module in `dist/umd/*`. However, the main distribution is built with TypeScript compiler without any bundling step.

I think the most straightforward solution here is to remove the `unicode-12.1.0` dependency and directly inline this single regex usage.
