### ISSUE TITLE
Passing filename to overrideIdFn

### ISSUE THREAD

**Issue by nmbrone** [formatjs/formatjs-old#495]
**Which package?**
babel-plugin-react-intl

**Is your feature request related to a problem? Please describe.**
Since we already provide the function for overriding a message ID, why not make it even more flexible by extending a set of available parameters with a filename? Please correct me if I'm wrong but the implementation shouldn't be complicated since we already use the filename for extracted messages.

**Describe the solution you'd like**
I'll prepare the draft implementation.

**Describe alternatives you've considered**

**Additional context**

**Comment by longlho** [comment]
what's ur use case?

**Comment by nmbrone** [comment]
Let's say I'm preferring to have IDs for messages based on file names but I'm also too lazy (probably as many other people are) to do it manually. 
And instead to write this:

```javascript
// src/components/dashboard/Dashboard.jsx
<FormattedMessage id="components.dashboard.Dashboard.one" defaultMessage="Message 1" />
<FormattedMessage id="components.dashboard.Dashboard.two" defaultMessage="Message 2" />
```

I'd like to write this:

```javascript
<FormattedMessage id="one" defaultMessage="Message 1" />
<FormattedMessage id="two" defaultMessage="Message 2" />
```

But still have full IDs in extracted messages:

```json
{
  "components.dashboard.Dashboard.one": "Message 1",
  "components.dashboard.Dashboard.two": "Message 2"
}
```

Which can be easily achieved by:

```javascript
{
  overrideIdFn: (id, defaultMessage, description, file) => {
    return file
      .replace(path.extname(file), '')
      .split(path.sep)
      .concat(id)
      .join('.');
  },
}
```

**Comment by nmbrone** [comment]
Any thoughts on this?
