### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Cuantico** [formatjs/formatjs-old#522]
**Which package?**
Since this is a monorepo. Please specify which package this bug report is for.

Failed to compile
./node_modules/react-intl/lib/utils.js
Attempted import error: 'invariant' is not exported from '@formatjs/intl-utils'.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longlho** [comment]
Do you have a codesandbox repro link?

**Comment by Cuantico** [comment]
From codesandbox
Something went wrong
Error importing GitHub repository: Request failed with status code 422

but this is the repo if it helps
https://github.com/Cuantico/planesdegobierno

**Comment by longlho** [comment]
hmm I don't see anything wrong w/ building or serving from the repo.

**Comment by Cuantico** [comment]
everything seems back to normal in the version   "@formatjs/intl-relativetimeformat": "^4.5.11",
