### ISSUE TITLE
Support react-intl-phraseapp for extracting messages

### ISSUE THREAD

**Issue by BramDecuypere** [formatjs/formatjs-old#530]
**Which package?**
formatjs/cli

**Is your feature request related to a problem? Please describe.**
I'm unable to extract the messages from my codebase.

**Describe the solution you'd like**
Extracting to locale files directly instead of an array of files? Or should we do the mapping ourselves? I guess you are checking on a certain package name to be in the folder? Maybe it would be nice to have optional packages? For when people extend the react-intl package like phrase(app).com did?

**Describe alternatives you've considered**

**Additional context**

**Comment by longlho** [comment]
Can you describe your use case in more details pls?

**Comment by BramDecuypere** [comment]
Thanks for the fast response!

Either I'm not using it as expected, or it's another feature:
```
"extract": "formatjs extract ./src/**/*.{js,jsx} --module-source-name 'react-intl-phraseapp' --out-file ./temp/test.json",
```

**Comment by BramDecuypere** [comment]
Thanks for the amazingly fast response!

I was able to figure it out. This was doing exactly what was expected:
```
formatjs extract ./src/**/*.{js,jsx} --module-source-name react-intl-phraseapp --out-file ./temp/test.json
```
