### ISSUE TITLE
babel-plugin-react-intl skipping .tsx files

### ISSUE THREAD

**Issue by aminosman** [formatjs/formatjs-old#533]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
Messages in .tsx files are not being extracted

**To Reproduce**
Create a .tsx file with some messages and run babel

**Comment by Callenowy** [comment]
Hey @aminosman, I had the same issue and found a workaround. Check out these posts:
https://mikebridge.github.io/post/typescript-i18n-react-intl/
https://medium.com/@yehiasaleh/internationalization-localization-using-react-intl-typescript-1e7cfccd34d7

**Comment by longlho** [comment]
do you have a repro link?
