### ISSUE TITLE
intl-displaynames locale data not minified under dist folder

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs-old#539]
**Which package?**
@formatjs/intl-displaynames

**Describe the bug**
The dist file doesn't seem to be minified 
https://unpkg.com/@formatjs/intl-displaynames@1.2.0/dist/locale-data/en.js

where other package locale data does minified. 
https://unpkg.com/browse/@formatjs/intl-relativetimeformat@4.5.9/dist/locale-data/en.js

**Expected behavior**
Same behavior across different formatjs packages

<img width="733" alt="Screen Shot 2020-02-27 at 7 05 49 PM" src="https://user-images.githubusercontent.com/3906130/75506884-36582680-5994-11ea-8142-b84db665b7c2.png">

**Comment by roderickhsiao** [comment]
Seems like its expected but just the template
https://github.com/formatjs/formatjs/blob/master/packages/intl-displaynames/scripts/cldr.ts#L45 is stringify with space and the template format with line break
https://github.com/formatjs/formatjs/blob/master/packages/intl-displaynames/scripts/cldr.ts#L66

I'll close this and doing uglify in our app

**Comment by longlho** [comment]
Hmm we should minify this.

**Comment by roderickhsiao** [comment]
I think umd file did have `.min` file running through uglily js, /dist file mostly just directly written from template string. 

Could be either way, let client to minify or we did it at publish.

I'll reopen and let you guys decide :)

**Comment by pyrocat101** [comment]
Fixed with 1.2.1 release.

**Comment by roderickhsiao** [comment]
awesome thanks
