### ISSUE TITLE
babel-plugin-react-intl: Custom XML tags not working in 6.0.0

### ISSUE THREAD

**Issue by Betree** [formatjs/formatjs-old#545]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
The upgrade [from 5.1.18 to 6.0.0](https://github.com/opencollective/opencollective-frontend/pull/3636) broke the strings where we have XML tags with a dash inside:

```jsx
<FormattedMessage
  id="ApplyToHostBtnLoggedIn.TOS"
  defaultMessage="I agree with the <tos-link>terms of fiscal sponsorship of the host</tos-link> ({hostName}) that will collect money on behalf of our collective."
  values={{
    hostName: host.name,
    'tos-link': msg => (
      <a href="#">
        {msg}
      </a>
    ),
  }}
/>
```

When trying to parse the above, we get an error message like:
> SyntaxError: ApplyToHostBtnLoggedIn.js: [React Intl] Message failed to parse. See: http://formatjs.io/guides/message-syntax/
SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.

**To Reproduce**

- Copy paste the message above in a project configured with `react-intl`
- Try to extract the messages

**Expected behavior**
- Either these tags should be supported.
- Or we could update the release note to specify that this pattern is not supported anymore (no problem with that on our side, just want to be sure before we go and update the strings).

**Additional context**
https://github.com/opencollective/opencollective-frontend/pull/3636

**Comment by ghost** [comment]
I have the same problem :(

`
"babel-plugin-react-intl": "5.1.18",
"intl-messageformat-parser": "4.0.0",
"react-intl": "3.12.1",
`

upd "babel-plugin-react-intl" to 6.0.0 version and there is still a problem
