### ISSUE TITLE
babel-plugin-react-intl doesn't update messages file if the corresponding module no longer contains any "message descriptors"

### ISSUE THREAD

**Issue by ervasive** [formatjs/formatjs-old#553]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
Let's say we have the following module (React component):

```jsx
import React from "react"
import { FormattedMessage } from "react-intl"

export default () => (
  <FormattedMessage
    id="test"
    defaultMessage="Test message"
    description="sample desc"
  />
)
```

When we update the `FormattedMessage` props, `babel-plugin-react-intl` updates (re-extracts) its values to a messages file (as intended):

```json
[
  {
    "id": "test",
    "description": "sample desc",
    "defaultMessage": "Test message"
  }
]
```

But if we update the module to the state when it doesn't have any "descriptors" in it, the messages file won't be updated and will contain stale values (instead of being empty):

```jsx
import React from "react"
import { FormattedMessage } from "react-intl"

export default () => (
  <p>No more FormattedMessage in this component</p>
)
```

```json
[
  {
    "id": "test",
    "description": "sample desc",
    "defaultMessage": "Test message"
  }
]
```

**To Reproduce**
I have prepared a codesandbox example running gatsby project.
- The `babel-plugin-react-intl` is enabled and configured in `gatsby-node.js` file
- The module containing the `FormattedMessage` component is defined within `src/pages/index.js`
- Messages are extracted to `messages` directory

1. Go to the [codesandbox demo project](https://codesandbox.io/s/babel-plugin-react-intl-demo-l1ysw)
2. Open `src/pages/index.js`
3. Update `FormattedMessage` props
4. Wait for gatsby to rebuild the dev bundle
5. Check extracted messages in `messages/src/pages/index.js` (it should reflect the updated values)
6. Remove the `FormattedMessage`, so the module does not contain any
7. Wait for gatsby to rebuild the dev bundle
8. Check the messages file

**Expected behavior**
The messages file should be empty or contain an empty array

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by paulincai** [comment]
Ok, @longlho after updating to 6.1.0 I ended up with 408 extra files which I don't need. What I did was to update the library and start my project in development.

I don't this this was the intended behavior. There are files created for each and every js file I have in my entire project structure, even for files that are just libraries, utilities etc...

![Screen Shot 2020-03-19 at 00 21 45](https://user-images.githubusercontent.com/26188915/77004010-d1329800-6977-11ea-9b7a-f03065454314.png)

**Comment by longlho** [comment]
@paulincai should be fixed in latest version

**Comment by ervasive** [comment]
I've updated the dependency in the [codesandbox](https://codesandbox.io/s/babel-plugin-react-intl-demo-ndn3v) example to the latest version and unfortunately, it still keeps non-existent (stale) "descriptors" for me in the messages file with v6.2.0 🤷

**Comment by ervasive** [comment]
NVM, just noticed the new option
Thank you for fixing the issue
