### ISSUE TITLE
Unnecessary Intl.PluralRules check causing problems in some browsers

### ISSUE THREAD

**Issue by HitkoDev** [formatjs/formatjs-old#558]
**Which package?**
intl-messageformat

**Describe the bug**
https://github.com/formatjs/formatjs/blob/b262d6d6d7d4914a379ed70f8a369438b7ba5ee6/packages/intl-messageformat/src/formatters.ts#L244-L254

This part throws when there's no `Intl.PluralRules` implementation, even when `formatters.getPluralRules` uses a custom implementation which doesn't require `Intl.PluralRules`. 

**To Reproduce**
See description.

**Expected behavior**
See description.

**Comment by longlho** [comment]
Can you clarify your use case?

**Comment by HitkoDev** [comment]
What's there to clarify? Maybe I just don't want a rather large polyfill when I already have a tiny function that does exactly what `getPluralRules.select` does?

Anyway, does it really matter? There's a documented public API that allows for custom formatters, and it shouldn't throw errors for something that's not needed, no matter what the use case may be.

**Comment by longlho** [comment]
That API is not public just because you found and export :)

**Comment by HitkoDev** [comment]
No, that API is public because it's listed as such in README: https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/README.md#public-api

**Comment by HitkoDev** [comment]
Also there's no such check for `Intl.NumberFormat` and `Intl.DateTimeFormat`, and custom `getNumberFormat` / `getDateTimeFormat` implementations work without a problem, so there's no logical need for this check, other than to promote `@formatjs/intl-pluralrules` polyfill (as noted in README, number & date formatters use third-party polyfills 😉 ).

**Comment by longlho** [comment]
We don't check for those because we only support IE11+ as the oldest browser which has `DateTimeFormat` & `NumberFormat`. As the doc mentioned we require `Intl.PluralRules` to be there as runtime requirements and custom formatters override are only used for caching purposes.

**Comment by HitkoDev** [comment]
If that's the case, why even mention polyfills for date & numbers anywhere, and why not turn caching into a simple bool flag instead of making a full interface that allows overrides?

**Comment by longlho** [comment]
We don't dictate caching strategy per formatters since they have different implications in browser vs SSR. Doing that via a boolean also means exposing cache itself to flush/purge/add on demand for finer grain control which is even worse.
