### ISSUE TITLE
[intl-locales-supported] can't require package

### ISSUE THREAD

**Issue by andban** [formatjs/formatjs-old#56]
### Which package?

intl-locales-supported

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

BUG REPORT

### Expected behavior

No error on require

### Current behavior

The published file `lib/index.js` contains es6 only code:
```js
export default function areIntlLocalesSupported(locales)
```

Which results in `SyntaxError: Unexpected token export`

### Step to reproduce for BUG REPORT
`const areLocalesSupported = require('intl-locales-supported')`

### Your Environment 

| Executable | Version |
| ---: | :--- |
| `npm ls <package name>` | 1.0.8 |
| `npm --version` | 5.6.0 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS High Sierra| 10.13.6 |

**Comment by andban** [comment]
Sorry, just saw that there is already a pull-request (#54) for this issue.

**Comment by willdurand** [comment]
> Sorry, just saw that there is already a pull-request (#54) for this issue.

Is this PR actually fixing the problem you reported here? I also have the exact same issue as you described, and I don't think #54 addresses it.

You should probably reopen this issue :)

**Comment by andban** [comment]
@willdurand Yes, you are right. That apparently doesn't do the trick, I let me get fooled by the title.

**Comment by okuryu** [comment]
#54 has been merged, and `intl-locales-supported@1.0.10` is published. Please try to test again.

**Comment by andban** [comment]
Just checked it and I can require the package again. Thanks!

**Comment by willdurand** [comment]
Same here, thanks!
