### ISSUE TITLE
intl-locales-supported NPM should get a major version bump

### ISSUE THREAD

**Issue by cdeutsch** [formatjs/formatjs-old#57]
### Which package?

intl-locales-supported

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

Just upgraded to `intl-locales-supported@1.0.10` and my app broke

When you change an NPM's API it's best practice to give the package a major version bump (ie. 2.0.0)
https://docs.npmjs.com/about-semantic-versioning

**Comment by cdeutsch** [comment]
Simply changing from...

```
const areIntlLocalesSupported = require('intl-locales-supported');
```

...to....

```
const areIntlLocalesSupported = require('intl-locales-supported').default;
```

...fixed it for me, but I'd still consider that an API change.

**Comment by longlho** [comment]
Sorry for the breakage, `default` module interop has consistently been an issue with upstream toolchain. Are you using a specific toolchain to consume this or just Node? We added `module` field to our `package.json` that exposes ES6 syntax, but `index.js` export is [the same](https://github.com/formatjs/formatjs/blob/master/packages/intl-locales-supported/index.js)

**Comment by cdeutsch** [comment]
I see. Yeah might be something specific to my toolchain. Feel free to close if you don't think it's an issue.

Thanks for the quick response 👍

**Comment by alasdairhurst** [comment]
Looks like there's still a breaking change somewhere. We've been using react-intl-loader which depends on intl-locales-supported "^1.0.0" and now since the new versions have been published it's throwing errors all over. 

```
    TypeError: isIntlLocaleSupported is not a function
        at ../../node_modules/react-intl-loader/index.js?locale=es!./test/intl/es.json.module.exports (webpack:///test/intl/es.json?e46f:4:0 <- test/loadtests.js:190703:7)
```

There is webpack dotted in there which isn't purely node but still this should ideally just keep working on the same major version.

**Comment by longlho** [comment]
We added the `module` field to `package.json` which signals upstream toolchain to prefer importing ES6 instead & in ES6 `default` export is stricter.
What does your usage look like?

**Comment by alasdairhurst** [comment]
Our usage (using this module via react-intl-loader and webpack) looks like this:
```
require('react-intl-loader?locale=en!./messages/en.json')((messages) => {
				res(messages);
			});
```

usage in react-intl-loader looks like this (don't ask why it's returning a string of source code, I didn't write it and don't know the ins and outs of webpack loaders)
https://github.com/danilobuerger/react-intl-loader/blob/master/index.js#L15

I did override the installed intl-locales-supported with 1.0.8 and it all worked as normal.

**Comment by alasdairhurst** [comment]
It's probably a dodgy/unconventional use case and pretty hard to read, but still it's probably better erring on the safe side reverting to keep 1.x functional  and going forward with 2.x

**Comment by longlho** [comment]
I can do that but unfortunately unless the upstream loader gets fixed or you migrate off of it you cannot up to 2.0 :( the dmg is kinda already been done. Can you open an issue in that loader? I’ll put in a PR there to fix.

**Comment by alasdairhurst** [comment]
We could do that, however there's likely a lot of other packages which will also have to be changed too which isn't great.
I think the correct approach would be to revert the 1.x range to be something that isn't broken/doesn't need any manual changes (i.e. republish 1.0.0, or whatever version is suitable as 1.0.11) and then anything using 1.x will continue working. The upgrade to 2.0 would be this manual change and include the recommended/required changes to be implemented to be used going forward (and then we can submit a PR to update this specific package which could be merged and released whenever)
