### ISSUE TITLE
formatjs-extract-cldr-data documentation doesn't reflect API

### ISSUE THREAD

**Issue by jasonmit** [formatjs/formatjs-old#584]
**Which package?**
formatjs-extract-cldr-data

**Describe the bug**
I'm planning to migrate ember-intl to the latest formatjs libs but currently blocked on the data extraction part since the APIs I realized on changed quite a bit.

The `formatjs-extract-cldr-data` [README](https://github.com/formatjs/formatjs/blob/master/packages/formatjs-extract-cldr-data/README.md) appears to be out of date and doesn't reflect the current API.  For example, the main module no longer exports a default function (`extractData`).  It now appears to export many utility functions.

Thanks in advance!  Love all the recent changes.

**Comment by longlho** [comment]
Hi there, sorry we didn't know you were using `formatjs-extract-cldr-data` by itself. Its usage is quite private to our monorepo only, which also means it's not really following semver and we can break things easily there whenever we change the way we massage CLDR data. We highly recommend you using our higher-level packages/API instead. 

What's your use case actually?

**Comment by jasonmit** [comment]
Prior was using it to extract plurals and relativetime data for the Ember formatjs integration.  I spent the week migrating ember-intl off those older libs and on to the new stuff.

I'll close this since not needed anymore.
