### ISSUE TITLE
Missing @babel/types dependency

### ISSUE THREAD

**Issue by bertho-zero** [formatjs/formatjs-old#586]
```
.babelrc.js: Error while loading config - babel-plugin-react-intl tried to access @babel/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

with Yarn 2

**Comment by longlho** [comment]
do you have a repro link (codesandbox/repo)?

**Comment by bertho-zero** [comment]
The require is visible in the first lines of
https://unpkg.com/babel-plugin-react-intl@7.1.0/dist/index.js but not in https://unpkg.com/babel-plugin-react-intl@7.1.0/package.json.
