### ISSUE TITLE
[babel-react-intl-plugin] Add an option to make defaultMessages optional

### ISSUE THREAD

**Issue by Ne3l** [formatjs/formatjs-old#59]
### Which package?

babel-plugin-react-intl

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

FEATURE REQUEST

### Expected behavior

In our case we build all the translations into a bundle. If any of this translations fails the build process crash. So in this context, we don't need the defaultMessages only the id of the translation.

Would be possible to add a property like `enforceDefaultMessage` that defaults to true but that we can overwrite to false to allow `<FormattedMessage id="key" />` ?

### Current behavior

There is not this option.

**Comment by longlho** [comment]
Yeah that should be do-able

**Comment by Ne3l** [comment]
Should i open a PR?

**Comment by longlho** [comment]
published in `3.2.0`
