### ISSUE TITLE
Link to monorepo in babel-plugin-react-intl goes to the wrong place

### ISSUE THREAD

**Issue by STRML** [formatjs/formatjs-old#63]
### Which package?

https://github.com/formatjs/babel-plugin-react-intl

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

This is a bug report.

### Expected behavior

The link to the monorepo should go to https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl.

### Current behavior

The link to the monorepo goes to https://github.com/formatjs/formatjs/tree/master/packages/intl-locales-supported.

I was unable to report on that repo because it is archived.

**Comment by longlho** [comment]
Thanks for reporting we'll do an audit of those links asap

**Comment by longlho** [comment]
fixed
