### ISSUE TITLE
Extract messages from packages

### ISSUE THREAD

**Issue by jahglow** [formatjs/formatjs-old#65]
Hello. I have parts of my react app as packages in node_modules that have their code use defineMessages and formatMessage. Though their code is not extracted into json files. Specifying babel rule to get node_modules parsed with this plugin doesn't give eny result either. Requiring a file that has defineMessages declared from node_modules and using one of the messages didn't give results. What am I doing wrongly and how can I extract those messages to have them translated? What is the workflow with modules that have their own translations?

**Comment by jahglow** [comment]
Hi, please reopen the issue. Sorry didn't reply, didn't see the question. It's too long to create a demo for that, and I have lots of wrk. But Ill describe the problem in greater details, maybe I'm missing something.

Say I have created a reusable React Component 'HelloWorld' which is published as an npm-repo :
messages.js:
```js
import {defineMessages} from 'react-intl'

export default defineMessages({
  pageTitle: {
    id: 'helloWorld.pageTitle',
    defaultMessage: 'Hello world!',
  }
})
```

index.js:
```js
import {IntlProvider, useIntl} from 'react-intl';
import messages from './messages';
export {default as messages} from './messages';

export default function HelloWorld(){
  const {formatMessage} = useIntl();
  return <H1>{formatMessage(messages.pageTitle)}</H1>
}
```

Then this component is used in an app:
```js
import {IntlProvider, useIntl} from 'react-intl';
import HelloWorld, {messages as helloWorldMessages} from 'hello-world-npm';
import translations from './translations/i18n'; //these are translations collected from local app modules via this babel plugin

const App= ()=>{
  const {formatMessage} = useIntl();
  return <H1>{formatMessage(messages.pageTitle)}</H1>
}

ReactDOM.render(
  <IntlProvider locale={'en'} messages={translations}>
    <App />
  </IntlProvider>,
  document.getElementById('container')
);
```

./translations/i18n.js
```js
const enTranslationMessages = require('./locales/en.json');
const ruTranslationMessages = require('./locales/ru.json');

export const appLocales = ['en', 'ru'];

export const formatTranslationMessages = messages =>
  Object.entries(messages || {}).reduce(
    (acc, [id, message, defaultMessage]) => Object.assign({}, acc, {[id]: message || defaultMessage}),
    {}
  );

export const translationMessages = {
  en: formatTranslationMessages(enTranslationMessages),
  ru: formatTranslationMessages(ruTranslationMessages),
};

```

these localse are bundled into translations via this script:
```js
const manageTranslations = require('react-intl-translations-manager').default;

manageTranslations({
  messagesDirectory: 'src/translations/extracted',
  translationsDirectory: 'src/translations/locales/',
  languages: ['ru', 'en'],
});
```

## The problem:
Babel plugin *doesn't collect* messages from node_modules, i.e. 'hello-world-npm' module, only from local files (`./src` folder), and as a result the messages don't appear in `extracted` folder hierarchy and do not end up in `locales` as a consequence

## The question:
How do I collect those messages? How can I publish and import npm modules that have react-intl messages usage and make them bundled with the project translations? Please reply ASAP

**Comment by longlho** [comment]
Yeah it does not collect from `node_modules`. What Yahoo and DBX do is every package aggregates its strings into a file, e.g `lang/strings_en-US.json` and they get merged upstream by the consumer, following the dependency tree declared in `package.json`.
