### ISSUE TITLE
How to use it with react native by just running a script without relying on build?

### ISSUE THREAD

**Issue by maamounapprise** [formatjs/formatjs-old#68]
Hi the library works great when i build on ios or android but what if I want a script to simply go over my messages.js and return a json file? 
I tried running 

`babel --plugins react-intl i18n/messages/*.js`

 but was simply outputing this 

`Object.defineProperty(exports,"__esModule",{value:true});exports.messages=void 0;var _reactIntl=require("react-intl");var messages=(0,_reactIntl.defineMessages)(login:{"id":"app.login","defaultMessage":"Login"}});exports.messages=messages;`

I also tried this: 

`"build:messages": "NODE_ENV=production babel ./ i18n/messages/*.js >/dev/null"`

I am using react native ^0.59.3 and metro-react-native-babel-preset 0.53.1

**Comment by longlho** [comment]
We might release a CLI. Seems like there's enough interest in making one.

**Comment by maamounapprise** [comment]
@longlho where could I follow this release you mentioned

**Comment by longlho** [comment]
I don't think there's been anything planned yet :) I'll keep this ticket open for tracking purpose when we do decide to implement that

**Comment by longlho** [comment]
We've released an early version of the CLI under https://www.npmjs.com/package/@formatjs/cli and looking for feedbacks!
