### ISSUE TITLE
version 1.6.0 not compatible with babel-plugin-react-intl

### ISSUE THREAD

**Issue by macca16** [formatjs/formatjs-old#7]
The default export of `intl-messageformat-parser` is not available in browser when using `1.6.0`
### Which package?

`intl-messageformat-parser`

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
BUG REPORT

### Expected behavior
requiring` intl-messageformat-parser` should provide an object with a default export containing the` .parse()` function

### Current behavior
Whilst `intl-messageformat` pegs the version to `1.4.0`, using `babel-plugin-react-intl ` the version of `intl-messageformat-parser` used will now be `1.6.0` resulting in the default export being missing when used from the browser. 

This is due to this line `"browser": "dist/parser.js",` in `packages/intl-messageformat-parser/package.json` which side steps `packages/intl-messageformat-parser/index.js` and prevents the default export from being set as expected.

### Step to reproduce for BUG REPORT
This should in theory affect any project using npm and `babel-plugin-react-intl` since the update of `intl-messageformat-parser` to `1.6.0` 

### Your Environment

| Executable | Version |
| npm | 5.6.0 |
| `node --version` | v8.9.4 |

+-- babel-plugin-react-intl@3.0.1                                                                                              
| `-- intl-messageformat-parser@1.6.0                                                                                                                                                                                  
+-- react-intl@2.9.0                                                                                                           
| `-- intl-messageformat@2.2.0                                                                                                 
|   `-- intl-messageformat-parser@1.4.0    

| OS | Version |
| Windows | Version	10.0.17134 Build 17134 |

| Browser | Version |
| Chrome | Version 74.0.3729.157 (Official Build) (64-bit) |

**Comment by longlho** [comment]
fixed in `1.6.2`
