### ISSUE TITLE
Blank defaultMessage should not throw error

### ISSUE THREAD

**Issue by eduardoinnorway** [formatjs/formatjs-old#70]
When you build language files with "yarn extract-intl"

SyntaxError: unknown: [React Intl] Message Descriptors require an id and defaultMessage. ✓

This should NOT throw and error on blank defaultMessage, a warning yes, but not error.

The reason you build is to have someone else write the texts based on the keys on the generate language files, so a blank defaultMessage error has no value here.

**Comment by longlho** [comment]
Fixed via #61
