### ISSUE TITLE
ASCII/Unicode information character separator are not accepted in the message format

### ISSUE THREAD

**Issue by aurambaj** [formatjs/formatjs-old#72]
Hello!

Any reason why the ASCII/Unicode information character separator are not accepted in the message format? I think related code is here: https://github.com/yahoo/intl-messageformat-parser/blob/master/src/parser.pegjs#L158

Can we accept those? range from ASCII 28 to 31 (not sure why other control character are excluded either but I don't need those)  

Thanks!

**Comment by longlho** [comment]
@pyrocat101 	u might have fixed this right?

**Comment by pyrocat101** [comment]
@longlho Yes this is fixed.
