### ISSUE TITLE
rules for named arguments

### ISSUE THREAD

**Issue by redbugz** [formatjs/formatjs-old#73]
Periods are not allowed in arguments names, but dashes are. I tried reading the ICU Message docs, but they don't seem very clear to me about what a valid identifier is. It just mentions :Pattern_Syntax: which I couldn't find a definitive answer for that I could understand.
messageformat.js in their parser comments this rule as "only allow valid javascript identifiers" but the dash is not allowed in a valid javascript identifier.

I was just curious where the rules come from about what a valid identifier syntax is.

I would love to use hierarchal properties or key paths in my expressions, but it's not allowed, and I was trying to understand if it's a limitation of the ICU Message "spec" or just a design decision of this implementation. I know it can lead to ambiguities and implementation headaches.

```
> parser.parse('{parent}')
{ type: 'messageFormatPattern',
  elements: [ { type: 'argumentElement', id: 'parent', format: null } ] }
> parser.parse('{parent.child}')
SyntaxError: Expected ",", "}" or [^ \t\n\r,.+={}#] but "." found.
> parser.parse('{parent-child}')
{ type: 'messageFormatPattern',
  elements: [ { type: 'argumentElement', id: 'parent-child', format: null } ] }
```

**Comment by longlho** [comment]
dupe of #72

**Comment by raghavbk** [comment]
is this issue fixed ?

**Comment by longlho** [comment]
it is
