### ISSUE TITLE
Cache AST serverside

### ISSUE THREAD

**Issue by laurentvd** [formatjs/formatjs-old#74]
I've done some measurements and it seems that parsing the messages to AST before supplying it to `IntlMessageFormat` saves about 80% of the rendering time. Since I have a lot of localized messsages in my app, I'd like to calculate the AST on the serverside (and cache them). I looked around and it seems the AST format is specific to this package. Is this correct? Do you have any ideas on how this can be achieved using PHP as a server-side language? It seems PHP's `http://php.net/manual/en/class.messageformatter.php` doesn't have any build in way to achieve this.

**Comment by longlho** [comment]
This is supported I believe https://github.com/formatjs/react-intl/blob/master/docs/API.md#advanced-usage
