### ISSUE TITLE
Combination of specified units + narrow distances fail

### ISSUE THREAD

**Issue by swernerx** [formatjs/formatjs-old#79]
We are using intl-relativeformat inside react-intl to show a human readable date indicator like "Today", "Tomorrow" in front of the actual date.

Our code looks like this:

```
<FormattedRelative value={date} units='day' />
```

We recently discovered a bug which is quite ugly. We see things like "Yesterday" combined with todays date which is clearly a failure.

It seems to work fine when the `date` is in the middle of the day e.g. noon, but does not work for example in the night hours where relative formatting moves it into the previous day.

I checked out the repository and tried reproducing it. Indeed this was not very hard.

I added an additional helper to return todays day in the early morning:

```js
function early() {
    return new Date().setHours(1);
}
```

I then used that exact method inside the test suite:

```js
            it('should always output in the specified units', function () {
                var rf = new IntlRelativeFormat('en', {units: 'day'});

                expect(rf.format(now())).to.equal('today');
->              expect(rf.format(early())).to.equal('today');
                expect(rf.format(past(24 * 60 * 60 * 1000))).to.equal('yesterday');
                expect(rf.format(past(30 * 24 * 60 * 60 * 1000))).to.equal('30 days ago');
                expect(rf.format(future(24 * 60 * 60 * 1000))).to.equal('tomorrow');
                expect(rf.format(future(30 * 24 * 60 * 60 * 1000))).to.equal('in 30 days');
            });
```

It fails with this error:

```
1) IntlRelativeFormat #resolvedOptions() units should always output in the specified units:
     Error: expected 'yesterday' to equal 'today'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Context.<anonymous> (tests/index.js:158:47)
```

**Comment by longlho** [comment]
fixed in #45
