### ISSUE TITLE
intl-locales-supported - latest - "areIntlLocalesSupported is not a function"

### ISSUE THREAD

**Issue by mageshwarang** [formatjs/formatjs-old#88]
**Which package?**
intl-locales-supported - version-1.1.0

**Describe the bug**
The function `areIntlLocalesSupported` is available in the `intl-locales-supported` package (https://github.com/formatjs/formatjs/blob/master/packages/intl-locales-supported/index.js). But the usage expects it.

I am get the following exception due to this,
`TypeError: areIntlLocalesSupported is not a function`

**Comment by okuryu** [comment]
We recently have the similar issues (#60, #56). I don't know what has changed in the recently released `intl-locales-supported@1.1.0`, do you see the same result in `intl-locales-supported@1.0.9`? It may be need more repro info on your problem.

**Comment by longlho** [comment]
It's the same issue in 1.0.9/1.0.10. Your toolchain probably picked up the ES module version. You can either change to ES import like `import areIntlLocalesSupported from 'intl-locales-supported'` or do `const areIntlLocalesSupported = require('intl-locales-supported').default`

**Comment by mageshwarang** [comment]
I see it's been updated here in this commit - https://github.com/formatjs/formatjs/compare/intl-locales-supported@1.0.1...master#diff-43357136c31c762f818f43007e32534b.

>It's the same issue in 1.0.9/1.0.10. Your toolchain probably picked up the ES module version. You can either change to ES import like import areIntlLocalesSupported from 'intl-locales-supported' or do const areIntlLocalesSupported = require('intl-locales-supported').default

Thanks for the suggestion.  I will check on this and post back.

**Comment by asaduryan** [comment]
> It's the same issue in 1.0.9/1.0.10. Your toolchain probably picked up the ES module version. You can either change to ES import like `import areIntlLocalesSupported from 'intl-locales-supported'` or do `const areIntlLocalesSupported = require('intl-locales-supported').default`

Thanks it help me
