### ISSUE TITLE
metadata['react-intl'].messages not set

### ISSUE THREAD

**Issue by nicolaeolteanu** [formatjs/formatjs-old#92]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
`metadata` not populated as it was in previous version `3.1.3`

**Expected behavior**
As per specification the response after transform should contain metadata with all messages found in the code.

`require('@babel/core').transform('code', { plugins: ['react-intl'] }) // => { code, map, ast, metadata['react-intl'].messages };`,

but the response contain `metadata` as empty object.

**Solution**
Populate `metadata['react-intl'].messages` in `post()` callback with descriptors as it was before.

**Comment by longlho** [comment]
@nicolaeolteanu 	thanks for reporting. Do you mind pointing me to the spec for `metadata`?

**Comment by nicolaeolteanu** [comment]
last line from https://github.com/formatjs/formatjs/blob/master/packages/babel-plugin-react-intl/README.md

**Comment by nicolaeolteanu** [comment]
If you have a look on the code before babel 7 refactor at line 220 `file.metadata['react-intl'] = { messages: descriptors };` source file `packages/babel-plugin-react-intl/src/index.js`

**Comment by longlho** [comment]
> last line from [/packages/babel-plugin-react-intl/README.md@`master`](https://github.com/formatjs/formatjs/blob/master/packages/babel-plugin-react-intl/README.md) [](/formatjs/formatjs/blob/HEAD@{2019-06-18T14:12:26Z}/packages/babel-plugin-react-intl/README.md)

Ah gotcha sorry about that. Putting up a fix now

**Comment by nicolaeolteanu** [comment]
Thank you for the fast reply!

**Comment by longlho** [comment]
`3.3.3` should have the fix. Thanks for reporting!
