### ISSUE TITLE
Number skeletons support for intl-messageformat

### ISSUE THREAD

**Issue by pyrocat101** [formatjs/formatjs-old#93]
**Which package?**
intl-messageformat

**Is your feature request related to a problem? Please describe.**
Number skeleton: https://github.com/unicode-org/icu/blob/master/docs/userguide/format_parse/numbers/skeletons.md

**Describe the solution you'd like**
Implement number skeleton parser.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pyrocat101** [comment]
See https://github.com/formatjs/formatjs/pull/131

**Comment by longlho** [comment]
We now have number format skeleton support in `intl-messageformat@7.7.0` now :)
